"""Canonical Barbarian Sim plugin entrypoint."""

from bunnyland.simpacks.barbariansim.mechanics import (
    ArmorComponent,
    AttackHandler,
    BarbarianSimPolicyComponent,
    BaseClaimComponent,
    BaseClaimedEvent,
    BlessingComponent,
    BlessingReceivedEvent,
    BossComponent,
    BossDefeatedEvent,
    BridgeSurvivalGapHandler,
    BuildingComponent,
    BuildingDecayedEvent,
    BuildingDemolishedEvent,
    BuildingUpgradedEvent,
    ChallengeHandler,
    CharacterPoisonedEvent,
    ClaimBaseHandler,
    ClaimTreasureHandler,
    CleanseCorruptionHandler,
    ClimbHandler,
    ClimbingGateComponent,
    ClimbingGatePassedEvent,
    ClimbingSkillComponent,
    CommandFollowerHandler,
    CorruptionCleansedEvent,
    CorruptionComponent,
    CorruptionGainedEvent,
    CurseComponent,
    CurseReceivedEvent,
    DangerZoneComponent,
    DangerZoneExploredEvent,
    DecayBuildingHandler,
    DefeatBossHandler,
    DefendHandler,
    DefendingComponent,
    DemolishBuildingHandler,
    DisarmTrapHandler,
    DurabilityComponent,
    ExploreDangerZoneHandler,
    ExposureChangedEvent,
    ExposureDamageEvent,
    FollowerComponent,
    FollowerOrderChangedEvent,
    FollowerRecruitedEvent,
    FortificationComponent,
    FortifyHandler,
    FrostbiteStartedEvent,
    GainCorruptionHandler,
    HeatstrokeStartedEvent,
    ItemBrokenEvent,
    ItemDamagedEvent,
    ItemRepairedEvent,
    PerformRitualHandler,
    PickpocketHandler,
    PlaceTrapHandler,
    PoisonCharacterHandler,
    PoisonComponent,
    PoisonProgressedEvent,
    PoisonTreatedEvent,
    PrepareSiegeHandler,
    PurgeWaveComponent,
    PurgeWaveStartedEvent,
    RaidHandler,
    RecruitFollowerHandler,
    ReleaseThrallHandler,
    RepairItemHandler,
    RitualComponent,
    RitualPerformedEvent,
    ShelterComponent,
    ShrineComponent,
    SiegePreparedEvent,
    SiegeReadinessComponent,
    SparHandler,
    StaminaChangedEvent,
    StaminaComponent,
    StartPurgeWaveHandler,
    SubdueHandler,
    SurvivalGapBridgedEvent,
    SurvivalGapComponent,
    TemperatureExposureComponent,
    TemperatureResistanceComponent,
    ThrallComponent,
    ThrallReleasedEvent,
    ThrallTakenEvent,
    TrapComponent,
    TrapDisarmedEvent,
    TrapPlacedEvent,
    TreasureClaimedEvent,
    TreasureComponent,
    TreasureUnlockedEvent,
    TreatPoisonHandler,
    UnlockTreasureHandler,
    UpgradeBuildingHandler,
    WeaponComponent,
    barbariansim_fragments,
    install_barbariansim,
)

from ...plugins.ids import (
    BARBARIANSIM,
    CORE_VERBS,
)
from ...plugins.model import (
    CommandContribution,
    ContentContribution,
    DependencyContribution,
    EcsContribution,
    Plugin,
    PluginPlacement,
    RuntimeContribution,
)
from .actions import ACTION_DEFINITIONS
from .demos import BARBARIANSIM_DEMO
from .generation import CAPABILITIES, GENERATION_ENRICHER
from .incidents import BARBARIAN_RAID
from .integration_3d import install_barbariansim_3d


def _definition() -> Plugin:
    return Plugin(
        id=BARBARIANSIM,
        name="Barbarian Sim",
        dependencies=DependencyContribution(
            requires=(CORE_VERBS,),
            integrates_with=(
                "bunnyland.colonysim",
                "bunnyland.storyteller",
                "bunnyland.3d",
            ),
        ),
        ecs=EcsContribution(
            components=(
                WeaponComponent,
                ArmorComponent,
                PoisonComponent,
                CorruptionComponent,
                DefendingComponent,
                DurabilityComponent,
                FortificationComponent,
                BaseClaimComponent,
                TrapComponent,
                StaminaComponent,
                TemperatureResistanceComponent,
                ShelterComponent,
                TemperatureExposureComponent,
                ThrallComponent,
                FollowerComponent,
                BarbarianSimPolicyComponent,
                SurvivalGapComponent,
                BuildingComponent,
                SiegeReadinessComponent,
                PurgeWaveComponent,
                ShrineComponent,
                RitualComponent,
                BlessingComponent,
                CurseComponent,
                DangerZoneComponent,
                BossComponent,
                TreasureComponent,
                ClimbingSkillComponent,
                ClimbingGateComponent,
            )
        ),
        commands=CommandContribution(
            action_definitions=ACTION_DEFINITIONS,
            action_handlers=(
                AttackHandler,
                SparHandler,
                DefendHandler,
                ChallengeHandler,
                FortifyHandler,
                ClaimBaseHandler,
                PlaceTrapHandler,
                DisarmTrapHandler,
                RaidHandler,
                BridgeSurvivalGapHandler,
                DecayBuildingHandler,
                UpgradeBuildingHandler,
                DemolishBuildingHandler,
                PrepareSiegeHandler,
                StartPurgeWaveHandler,
                PerformRitualHandler,
                ExploreDangerZoneHandler,
                DefeatBossHandler,
                UnlockTreasureHandler,
                ClaimTreasureHandler,
                ClimbHandler,
                RepairItemHandler,
                PoisonCharacterHandler,
                TreatPoisonHandler,
                GainCorruptionHandler,
                CleanseCorruptionHandler,
                PickpocketHandler,
                SubdueHandler,
                RecruitFollowerHandler,
                CommandFollowerHandler,
                ReleaseThrallHandler,
            ),
            typed_events=(
                StaminaChangedEvent,
                ExposureChangedEvent,
                HeatstrokeStartedEvent,
                FrostbiteStartedEvent,
                ExposureDamageEvent,
                ItemDamagedEvent,
                ItemBrokenEvent,
                ItemRepairedEvent,
                BaseClaimedEvent,
                TrapPlacedEvent,
                TrapDisarmedEvent,
                CharacterPoisonedEvent,
                PoisonProgressedEvent,
                PoisonTreatedEvent,
                CorruptionGainedEvent,
                CorruptionCleansedEvent,
                ThrallTakenEvent,
                FollowerRecruitedEvent,
                FollowerOrderChangedEvent,
                ThrallReleasedEvent,
                SurvivalGapBridgedEvent,
                BuildingDecayedEvent,
                BuildingUpgradedEvent,
                BuildingDemolishedEvent,
                SiegePreparedEvent,
                PurgeWaveStartedEvent,
                RitualPerformedEvent,
                BlessingReceivedEvent,
                CurseReceivedEvent,
                DangerZoneExploredEvent,
                BossDefeatedEvent,
                TreasureUnlockedEvent,
                TreasureClaimedEvent,
                ClimbingGatePassedEvent,
            ),
        ),
        runtime=RuntimeContribution(
            service_factories=(install_barbariansim,),
            integration_factories=(install_barbariansim_3d,),
        ),
        content=ContentContribution(
            prompt_fragments=(barbariansim_fragments,),
            generation_capabilities=CAPABILITIES,
            generation_enrichers=(GENERATION_ENRICHER,),
            world_generators=(BARBARIANSIM_DEMO,),
            incident_definitions=(BARBARIAN_RAID,),
        ),
    )


def plugin() -> Plugin:
    return _definition().model_copy(update={"placement": PluginPlacement.OUTER})


def bunnyland_plugins() -> list[Plugin]:
    return [plugin()]


__all__ = ["bunnyland_plugins", "plugin"]
