"""voidsim generation contribution compatibility surface."""

from ...worldgen.enrichment import LegacyWorldgenEnricher, VoidWorldgenHook

CAPABILITIES = (
    "bunnyland.voidsim.airlock",
    "bunnyland.voidsim.alien-artifact",
    "bunnyland.voidsim.alien-species",
    "bunnyland.voidsim.astrogation",
    "bunnyland.voidsim.away-team",
    "bunnyland.voidsim.blueprint",
    "bunnyland.voidsim.boarding-threat",
    "bunnyland.voidsim.cargo",
    "bunnyland.voidsim.contract",
    "bunnyland.voidsim.customs-hold",
    "bunnyland.voidsim.data-salvage",
    "bunnyland.voidsim.diplomatic-mission",
    "bunnyland.voidsim.distress-signal",
    "bunnyland.voidsim.drone",
    "bunnyland.voidsim.emergency",
    "bunnyland.voidsim.fabricator",
    "bunnyland.voidsim.first-contact",
    "bunnyland.voidsim.gravity",
    "bunnyland.voidsim.habitat-module",
    "bunnyland.voidsim.insurance-policy",
    "bunnyland.voidsim.jump-drive",
    "bunnyland.voidsim.mining-site",
    "bunnyland.voidsim.morale",
    "bunnyland.voidsim.mortgage",
    "bunnyland.voidsim.mutiny",
    "bunnyland.voidsim.navigation-route",
    "bunnyland.voidsim.orbit",
    "bunnyland.voidsim.orbital-body",
    "bunnyland.voidsim.passenger",
    "bunnyland.voidsim.quarantine",
    "bunnyland.voidsim.reactor",
    "bunnyland.voidsim.salvage-claim",
    "bunnyland.voidsim.sensor",
    "bunnyland.voidsim.ship",
    "bunnyland.voidsim.ship-ai",
    "bunnyland.voidsim.ship-system",
    "bunnyland.voidsim.ship-upgrade",
    "bunnyland.voidsim.smuggling-compartment",
    "bunnyland.voidsim.star-system",
    "bunnyland.voidsim.station",
    "bunnyland.voidsim.survey-site",
    "bunnyland.voidsim.trade-protocol",
    "bunnyland.voidsim.translation-matrix",
    "bunnyland.voidsim.xenobiology-sample",
)
ALIASES = {
    "airlock": "bunnyland.voidsim.airlock",
    "alien-artifact": "bunnyland.voidsim.alien-artifact",
    "alien-species": "bunnyland.voidsim.alien-species",
    "astrogation": "bunnyland.voidsim.astrogation",
    "away-team": "bunnyland.voidsim.away-team",
    "blueprint": "bunnyland.voidsim.blueprint",
    "boarding-threat": "bunnyland.voidsim.boarding-threat",
    "cargo": "bunnyland.voidsim.cargo",
    "contract": "bunnyland.voidsim.contract",
    "customs-hold": "bunnyland.voidsim.customs-hold",
    "data-salvage": "bunnyland.voidsim.data-salvage",
    "diplomatic-mission": "bunnyland.voidsim.diplomatic-mission",
    "distress-signal": "bunnyland.voidsim.distress-signal",
    "drone": "bunnyland.voidsim.drone",
    "emergency": "bunnyland.voidsim.emergency",
    "fabricator": "bunnyland.voidsim.fabricator",
    "first-contact": "bunnyland.voidsim.first-contact",
    "gravity": "bunnyland.voidsim.gravity",
    "habitat-module": "bunnyland.voidsim.habitat-module",
    "insurance-policy": "bunnyland.voidsim.insurance-policy",
    "jump-drive": "bunnyland.voidsim.jump-drive",
    "mining-site": "bunnyland.voidsim.mining-site",
    "morale": "bunnyland.voidsim.morale",
    "mortgage": "bunnyland.voidsim.mortgage",
    "mutiny": "bunnyland.voidsim.mutiny",
    "navigation-route": "bunnyland.voidsim.navigation-route",
    "orbit": "bunnyland.voidsim.orbit",
    "orbital-body": "bunnyland.voidsim.orbital-body",
    "passenger": "bunnyland.voidsim.passenger",
    "quarantine": "bunnyland.voidsim.quarantine",
    "reactor": "bunnyland.voidsim.reactor",
    "salvage-claim": "bunnyland.voidsim.salvage-claim",
    "sensor": "bunnyland.voidsim.sensor",
    "ship": "bunnyland.voidsim.ship",
    "ship-ai": "bunnyland.voidsim.ship-ai",
    "ship-system": "bunnyland.voidsim.ship-system",
    "ship-upgrade": "bunnyland.voidsim.ship-upgrade",
    "smuggling-compartment": "bunnyland.voidsim.smuggling-compartment",
    "star-system": "bunnyland.voidsim.star-system",
    "station": "bunnyland.voidsim.station",
    "survey-site": "bunnyland.voidsim.survey-site",
    "trade-protocol": "bunnyland.voidsim.trade-protocol",
    "translation-matrix": "bunnyland.voidsim.translation-matrix",
    "xenobiology-sample": "bunnyland.voidsim.xenobiology-sample",
}
GENERATION_ENRICHER = LegacyWorldgenEnricher(VoidWorldgenHook, provided_capabilities=CAPABILITIES)

__all__ = ["GENERATION_ENRICHER", "VoidWorldgenHook"]
