"""gardensim generation contribution compatibility surface."""

from ...worldgen.enrichment import ComponentPlanEnricher, GardenWorldgenHook

CAPABILITIES = (
    "bunnyland.gardensim.animal-breeding",
    "bunnyland.gardensim.animal-home",
    "bunnyland.gardensim.animal-product",
    "bunnyland.gardensim.bundle",
    "bunnyland.gardensim.collection",
    "bunnyland.gardensim.crop",
    "bunnyland.gardensim.crop-growth",
    "bunnyland.gardensim.crop-inspection",
    "bunnyland.gardensim.crop-quality",
    "bunnyland.gardensim.daily-farm-reset",
    "bunnyland.gardensim.farm-animal",
    "bunnyland.gardensim.farm-quest",
    "bunnyland.gardensim.fertilizer",
    "bunnyland.gardensim.festival",
    "bunnyland.gardensim.fishing-spot",
    "bunnyland.gardensim.forage",
    "bunnyland.gardensim.friendship",
    "bunnyland.gardensim.garden-soil",
    "bunnyland.gardensim.geode",
    "bunnyland.gardensim.gift-preference",
    "bunnyland.gardensim.greenhouse",
    "bunnyland.gardensim.harvestable",
    "bunnyland.gardensim.ladder",
    "bunnyland.gardensim.machine",
    "bunnyland.gardensim.machine-breakdown",
    "bunnyland.gardensim.mail",
    "bunnyland.gardensim.mine-level",
    "bunnyland.gardensim.mining-node",
    "bunnyland.gardensim.museum-collection",
    "bunnyland.gardensim.pest",
    "bunnyland.gardensim.processing-recipe",
    "bunnyland.gardensim.regrowable",
    "bunnyland.gardensim.reward",
    "bunnyland.gardensim.seed",
    "bunnyland.gardensim.shipping-bin",
    "bunnyland.gardensim.soil",
    "bunnyland.gardensim.tilled",
    "bunnyland.gardensim.tree",
    "bunnyland.gardensim.tree-tap",
    "bunnyland.gardensim.watered",
    "bunnyland.gardensim.weed",
)
ALIASES = {
    "animal-breeding": "bunnyland.gardensim.animal-breeding",
    "animal-home": "bunnyland.gardensim.animal-home",
    "animal-product": "bunnyland.gardensim.animal-product",
    "bundle": "bunnyland.gardensim.bundle",
    "collection": "bunnyland.gardensim.collection",
    "crop": "bunnyland.gardensim.crop",
    "crop-growth": "bunnyland.gardensim.crop-growth",
    "crop-inspection": "bunnyland.gardensim.crop-inspection",
    "crop-quality": "bunnyland.gardensim.crop-quality",
    "daily-farm-reset": "bunnyland.gardensim.daily-farm-reset",
    "farm-animal": "bunnyland.gardensim.farm-animal",
    "farm-quest": "bunnyland.gardensim.farm-quest",
    "fertilizer": "bunnyland.gardensim.fertilizer",
    "festival": "bunnyland.gardensim.festival",
    "fishing-spot": "bunnyland.gardensim.fishing-spot",
    "forage": "bunnyland.gardensim.forage",
    "friendship": "bunnyland.gardensim.friendship",
    "garden-soil": "bunnyland.gardensim.garden-soil",
    "geode": "bunnyland.gardensim.geode",
    "gift-preference": "bunnyland.gardensim.gift-preference",
    "greenhouse": "bunnyland.gardensim.greenhouse",
    "harvestable": "bunnyland.gardensim.harvestable",
    "ladder": "bunnyland.gardensim.ladder",
    "machine": "bunnyland.gardensim.machine",
    "machine-breakdown": "bunnyland.gardensim.machine-breakdown",
    "mail": "bunnyland.gardensim.mail",
    "mine-level": "bunnyland.gardensim.mine-level",
    "mining-node": "bunnyland.gardensim.mining-node",
    "museum-collection": "bunnyland.gardensim.museum-collection",
    "pest": "bunnyland.gardensim.pest",
    "processing-recipe": "bunnyland.gardensim.processing-recipe",
    "regrowable": "bunnyland.gardensim.regrowable",
    "reward": "bunnyland.gardensim.reward",
    "seed": "bunnyland.gardensim.seed",
    "shipping-bin": "bunnyland.gardensim.shipping-bin",
    "soil": "bunnyland.gardensim.soil",
    "tilled": "bunnyland.gardensim.tilled",
    "tree": "bunnyland.gardensim.tree",
    "tree-tap": "bunnyland.gardensim.tree-tap",
    "watered": "bunnyland.gardensim.watered",
    "weed": "bunnyland.gardensim.weed",
}
GENERATION_ENRICHER = ComponentPlanEnricher(GardenWorldgenHook, provided_capabilities=CAPABILITIES)

__all__ = ["GENERATION_ENRICHER", "GardenWorldgenHook"]
