"""dragonsim generation contribution compatibility surface."""

from ...worldgen.enrichment import (
    ComponentPlanEnricher,
    DaggerWorldgenHook,
    DragonWorldgenHook,
)

CAPABILITIES = (
    "bunnyland.dragonsim.ancient-beast",
    "bunnyland.dragonsim.artifact",
    "bunnyland.dragonsim.bounty",
    "bunnyland.dragonsim.carvable",
    "bunnyland.dragonsim.discovery",
    "bunnyland.dragonsim.encounter-zone",
    "bunnyland.dragonsim.faction",
    "bunnyland.dragonsim.faction-reputation",
    "bunnyland.dragonsim.great-soul",
    "bunnyland.dragonsim.guard",
    "bunnyland.dragonsim.jail",
    "bunnyland.dragonsim.lock-difficulty",
    "bunnyland.dragonsim.locked",
    "bunnyland.dragonsim.lore-book",
    "bunnyland.dragonsim.magic",
    "bunnyland.dragonsim.map-marker",
    "bunnyland.dragonsim.perk",
    "bunnyland.dragonsim.persuasion",
    "bunnyland.dragonsim.point-of-interest",
    "bunnyland.dragonsim.potion",
    "bunnyland.dragonsim.potion-recipe",
    "bunnyland.dragonsim.quest",
    "bunnyland.dragonsim.quest-objective",
    "bunnyland.dragonsim.quest-reward",
    "bunnyland.dragonsim.quest-stage",
    "bunnyland.dragonsim.spell",
    "bunnyland.dragonsim.spell-cooldown",
    "bunnyland.dragonsim.stealth",
    "bunnyland.dragonsim.surrender",
    "bunnyland.dragonsim.voice-inscription",
    "bunnyland.dragonsim.wanted",
    "bunnyland.dragonsim.word-of-power",
)
ALIASES = {
    "ancient-beast": "bunnyland.dragonsim.ancient-beast",
    "artifact": "bunnyland.dragonsim.artifact",
    "bounty": "bunnyland.dragonsim.bounty",
    "carvable": "bunnyland.dragonsim.carvable",
    "discovery": "bunnyland.dragonsim.discovery",
    "encounter-zone": "bunnyland.dragonsim.encounter-zone",
    "faction": "bunnyland.dragonsim.faction",
    "faction-reputation": "bunnyland.dragonsim.faction-reputation",
    "great-soul": "bunnyland.dragonsim.great-soul",
    "guard": "bunnyland.dragonsim.guard",
    "jail": "bunnyland.dragonsim.jail",
    "lock-difficulty": "bunnyland.dragonsim.lock-difficulty",
    "locked": "bunnyland.dragonsim.locked",
    "lore-book": "bunnyland.dragonsim.lore-book",
    "magic": "bunnyland.dragonsim.magic",
    "map-marker": "bunnyland.dragonsim.map-marker",
    "perk": "bunnyland.dragonsim.perk",
    "persuasion": "bunnyland.dragonsim.persuasion",
    "point-of-interest": "bunnyland.dragonsim.point-of-interest",
    "potion": "bunnyland.dragonsim.potion",
    "potion-recipe": "bunnyland.dragonsim.potion-recipe",
    "quest": "bunnyland.dragonsim.quest",
    "quest-objective": "bunnyland.dragonsim.quest-objective",
    "quest-reward": "bunnyland.dragonsim.quest-reward",
    "quest-stage": "bunnyland.dragonsim.quest-stage",
    "spell": "bunnyland.dragonsim.spell",
    "spell-cooldown": "bunnyland.dragonsim.spell-cooldown",
    "stealth": "bunnyland.dragonsim.stealth",
    "surrender": "bunnyland.dragonsim.surrender",
    "voice-inscription": "bunnyland.dragonsim.voice-inscription",
    "wanted": "bunnyland.dragonsim.wanted",
    "word-of-power": "bunnyland.dragonsim.word-of-power",
}
GENERATION_ENRICHER = ComponentPlanEnricher(DragonWorldgenHook, provided_capabilities=CAPABILITIES)
GENERATED_QUEST_ENRICHER = ComponentPlanEnricher(DaggerWorldgenHook)

__all__ = ["GENERATED_QUEST_ENRICHER", "GENERATION_ENRICHER", "DragonWorldgenHook"]
