"""Canonical Dragon Sim plugin entrypoint."""

from bunnyland.simpacks.dragonsim.mechanics import (
    AbsorbGreatSoulHandler,
    AcceptQuestHandler,
    AncientBeastAppeasedEvent,
    AncientBeastComponent,
    AppeaseAncientBeastHandler,
    ArtifactComponent,
    ArtifactIdentifiedEvent,
    ArtifactUsedEvent,
    BountyPaidEvent,
    BrewPotionHandler,
    BribeGuardHandler,
    CarvableComponent,
    CastDragonSpellHandler,
    ChangeFactionRankHandler,
    ChooseQuestBranchHandler,
    CompleteObjectiveHandler,
    CrimeReportedEvent,
    CrimeWitnessedEvent,
    DeclineQuestHandler,
    DiscoverLocationHandler,
    DiscoveryComponent,
    DragonSpellCastEvent,
    EncounterTriggeredEvent,
    EncounterZoneComponent,
    FactionComponent,
    FactionJoinedEvent,
    FactionLeftEvent,
    FactionRankChangedEvent,
    FactionReputationComponent,
    GreatSoulAbsorbedEvent,
    GreatSoulComponent,
    GuardBribedEvent,
    GuardComponent,
    HasPerk,
    IdentifyArtifactHandler,
    InscribeVoicePhraseHandler,
    JailComponent,
    JailSentenceServedEvent,
    JoinFactionHandler,
    KnowsSpell,
    KnowsWord,
    LearnSpellHandler,
    LearnWordOfPowerHandler,
    LeaveFactionHandler,
    LocationDiscoveredEvent,
    LockDifficultyComponent,
    LockPickedEvent,
    LoreBookComponent,
    LoreBookReadEvent,
    MagicComponent,
    MagicRecoveredEvent,
    MapMarkerAddedEvent,
    MapMarkerComponent,
    MarkMapHandler,
    MemberOf,
    PayBountyHandler,
    PerkComponent,
    PerkUnlockedEvent,
    PersuadeHandler,
    PersuasionAttemptedEvent,
    PersuasionComponent,
    PickLockHandler,
    PointOfInterestComponent,
    PotionBrewedEvent,
    PotionComponent,
    PotionRecipeComponent,
    QuestAcceptedBy,
    QuestAcceptedEvent,
    QuestBranchChosenEvent,
    QuestCompletedEvent,
    QuestComponent,
    QuestDeclinedEvent,
    QuestHasObjective,
    QuestHasReward,
    QuestObjectiveCompletedEvent,
    QuestObjectiveComponent,
    QuestProvenanceComponent,
    QuestRewardComponent,
    QuestRewardGrants,
    QuestStateComponent,
    QuestTrackedEvent,
    ReadLoreBookHandler,
    RecoverMagicHandler,
    ReportCrimeHandler,
    RequiresQuest,
    ServeJailTimeHandler,
    SneakHandler,
    SneakingComponent,
    SpeakWordOfPowerHandler,
    SpellComponent,
    SpellCooldownComponent,
    SpellLearnedEvent,
    StealHandler,
    StealthChangedEvent,
    StudyVoiceInscriptionHandler,
    SurrenderComponent,
    SurrenderedEvent,
    SurrenderHandler,
    TheftCommittedEvent,
    TrackQuestHandler,
    TracksQuest,
    TriggerEncounterHandler,
    UnlockPerkHandler,
    UseArtifactHandler,
    VoiceInscriptionComponent,
    VoiceInscriptionStudiedEvent,
    VoicePhraseInscribedEvent,
    WantedComponent,
    WordOfPowerComponent,
    WordOfPowerLearnedEvent,
    WordOfPowerSpokenEvent,
    dragonsim_fragments,
)

from ...plugins.ids import (
    BARBARIANSIM,
    CORE_VERBS,
    DRAGONSIM,
    LIFESIM,
)
from ...plugins.model import (
    CommandContribution,
    ContentContribution,
    DependencyContribution,
    EcsContribution,
    Plugin,
    PluginPlacement,
    RuntimeContribution,
)
from .actions import ACTION_DEFINITIONS
from .demos import CLUE_SNACK_DEMO, DRAGONSIM_DEMO
from .generation import CAPABILITIES, GENERATED_QUEST_ENRICHER, GENERATION_ENRICHER
from .quests import (
    AbandonGeneratedQuestHandler,
    AcceptGeneratedQuestHandler,
    AskForWorkHandler,
    CompleteGeneratedQuestHandler,
    ExtendGeneratedQuestHandler,
    LieAboutQuestHandler,
    QuestAbandonedEvent,
    QuestDeadlineConsequence,
    QuestExtendedEvent,
    QuestFailedEvent,
    QuestGeneratedEvent,
    QuestLieToldEvent,
    QuestRefusedEvent,
    QuestTemplateComponent,
    RefuseGeneratedQuestHandler,
    generated_quest_fragments,
)
from .resolution import RESOLUTION_RULES


def _install_quest_deadlines(actor) -> None:
    actor.register_consequence(QuestDeadlineConsequence())


def _definition() -> Plugin:
    return Plugin(
        id=DRAGONSIM,
        name="Dragon Sim",
        dependencies=DependencyContribution(
            requires=(CORE_VERBS, LIFESIM),
            recommends=(BARBARIANSIM,),
        ),
        ecs=EcsContribution(
            components=(
                PointOfInterestComponent,
                DiscoveryComponent,
                MapMarkerComponent,
                EncounterZoneComponent,
                QuestComponent,
                QuestStateComponent,
                QuestProvenanceComponent,
                QuestObjectiveComponent,
                QuestRewardComponent,
                QuestTemplateComponent,
                FactionComponent,
                FactionReputationComponent,
                GuardComponent,
                JailComponent,
                PerkComponent,
                AncientBeastComponent,
                GreatSoulComponent,
                WordOfPowerComponent,
                CarvableComponent,
                VoiceInscriptionComponent,
                SneakingComponent,
                WantedComponent,
                LockDifficultyComponent,
                LoreBookComponent,
                MagicComponent,
                SpellCooldownComponent,
                SpellComponent,
                PersuasionComponent,
                SurrenderComponent,
                PotionRecipeComponent,
                PotionComponent,
                ArtifactComponent,
            ),
            edges=(
                MemberOf,
                HasPerk,
                KnowsWord,
                KnowsSpell,
                QuestHasObjective,
                QuestHasReward,
                QuestAcceptedBy,
                TracksQuest,
                RequiresQuest,
                QuestRewardGrants,
            ),
        ),
        commands=CommandContribution(
            action_definitions=ACTION_DEFINITIONS,
            action_handlers=(
                DiscoverLocationHandler,
                MarkMapHandler,
                TriggerEncounterHandler,
                AcceptQuestHandler,
                CompleteObjectiveHandler,
                TrackQuestHandler,
                DeclineQuestHandler,
                ChooseQuestBranchHandler,
                AskForWorkHandler,
                AcceptGeneratedQuestHandler,
                CompleteGeneratedQuestHandler,
                RefuseGeneratedQuestHandler,
                AbandonGeneratedQuestHandler,
                ExtendGeneratedQuestHandler,
                LieAboutQuestHandler,
                JoinFactionHandler,
                LeaveFactionHandler,
                ChangeFactionRankHandler,
                UnlockPerkHandler,
                AbsorbGreatSoulHandler,
                LearnWordOfPowerHandler,
                SpeakWordOfPowerHandler,
                InscribeVoicePhraseHandler,
                StudyVoiceInscriptionHandler,
                SneakHandler,
                StealHandler,
                PayBountyHandler,
                PersuadeHandler,
                SurrenderHandler,
                ReportCrimeHandler,
                BribeGuardHandler,
                ServeJailTimeHandler,
                PickLockHandler,
                ReadLoreBookHandler,
                LearnSpellHandler,
                CastDragonSpellHandler,
                RecoverMagicHandler,
                BrewPotionHandler,
                IdentifyArtifactHandler,
                UseArtifactHandler,
                AppeaseAncientBeastHandler,
            ),
            typed_events=(
                LocationDiscoveredEvent,
                MapMarkerAddedEvent,
                EncounterTriggeredEvent,
                QuestAcceptedEvent,
                QuestObjectiveCompletedEvent,
                QuestCompletedEvent,
                QuestTrackedEvent,
                QuestDeclinedEvent,
                QuestBranchChosenEvent,
                QuestGeneratedEvent,
                QuestFailedEvent,
                QuestRefusedEvent,
                QuestAbandonedEvent,
                QuestExtendedEvent,
                QuestLieToldEvent,
                FactionJoinedEvent,
                FactionLeftEvent,
                FactionRankChangedEvent,
                PerkUnlockedEvent,
                GreatSoulAbsorbedEvent,
                WordOfPowerLearnedEvent,
                WordOfPowerSpokenEvent,
                VoicePhraseInscribedEvent,
                VoiceInscriptionStudiedEvent,
                StealthChangedEvent,
                TheftCommittedEvent,
                CrimeWitnessedEvent,
                CrimeReportedEvent,
                BountyPaidEvent,
                PersuasionAttemptedEvent,
                SurrenderedEvent,
                GuardBribedEvent,
                JailSentenceServedEvent,
                LockPickedEvent,
                LoreBookReadEvent,
                SpellLearnedEvent,
                DragonSpellCastEvent,
                MagicRecoveredEvent,
                PotionBrewedEvent,
                ArtifactIdentifiedEvent,
                ArtifactUsedEvent,
                AncientBeastAppeasedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(_install_quest_deadlines,)),
        content=ContentContribution(
            prompt_fragments=(dragonsim_fragments, generated_quest_fragments),
            generation_capabilities=CAPABILITIES,
            generation_enrichers=(GENERATION_ENRICHER, GENERATED_QUEST_ENRICHER),
            incident_resolution_rules=RESOLUTION_RULES,
            world_generators=(DRAGONSIM_DEMO, CLUE_SNACK_DEMO),
        ),
    )


def plugin() -> Plugin:
    return _definition().model_copy(update={"placement": PluginPlacement.OUTER})


def bunnyland_plugins() -> list[Plugin]:
    return [plugin()]


__all__ = ["bunnyland_plugins", "plugin"]
