"""Action metadata owned by bunnyland.core_verbs."""

from ...core.actions import (
    FOCUS_COST,
    FREE_COST,
    SPEECH_COST,
    ActionDefinition,
    ActionPattern,
    define_action,
)
from ...core.commands import Lane

ACTION_DEFINITIONS: tuple[ActionDefinition, ...] = (
    define_action(
        "look",
        tool_name="look",
        cost=FREE_COST,
        patterns=(ActionPattern("look", {}), ActionPattern("look around", {})),
        examples=("look",),
    ),
    define_action(
        "inspect",
        ("target_id",),
        tool_name="inspect",
        patterns=("inspect {target_id}", "look at {target_id}", "examine {target_id}"),
        examples=("inspect woven basket",),
    ),
    define_action(
        "move",
        ("direction", "exit_id"),
        tool_name="move",
        patterns=(
            "go {direction}",
            "move {direction}",
            "walk {direction}",
            "run {direction}",
            "go {exit_id}",
            "move {exit_id}",
            "walk {exit_id}",
            "run {exit_id}",
            ActionPattern("north", {"direction": "north"}),
            ActionPattern("south", {"direction": "south"}),
            ActionPattern("east", {"direction": "east"}),
            ActionPattern("west", {"direction": "west"}),
            ActionPattern("up", {"direction": "up"}),
            ActionPattern("down", {"direction": "down"}),
            ActionPattern("inside", {"direction": "inside"}),
            ActionPattern("outside", {"direction": "outside"}),
            ActionPattern("in", {"direction": "in"}),
            ActionPattern("out", {"direction": "out"}),
        ),
        examples=("go north",),
    ),
    define_action(
        "take",
        ("item_id",),
        tool_name="take",
        patterns=(
            "take {item_id}",
            "get {item_id}",
            "grab {item_id}",
            "pick up {item_id}",
            "pick {item_id}",
        ),
        examples=("take brass key",),
    ),
    define_action(
        "put",
        ("item_id", "target_container_id"),
        tool_name="put",
        patterns=(
            "put {item_id} in {target_container_id}",
            "put {item_id} into {target_container_id}",
            "put {item_id} on {target_container_id}",
            "put {item_id} onto {target_container_id}",
        ),
    ),
    define_action(
        "drop",
        ("item_id",),
        tool_name="drop",
        patterns=("drop {item_id}", "put {item_id}"),
        examples=("drop brass key",),
    ),
    define_action(
        "open",
        ("target_id",),
        tool_name="open",
        patterns=("open {target_id}",),
        examples=("open woven basket",),
    ),
    define_action(
        "close",
        ("target_id",),
        tool_name="close",
        patterns=("close {target_id}",),
    ),
    define_action(
        "lock",
        ("target_id", "tool_id"),
        tool_name="lock",
        patterns=("lock {target_id} with {tool_id}", "lock {target_id}"),
    ),
    define_action(
        "unlock",
        ("target_id", "tool_id"),
        tool_name="unlock",
        patterns=("unlock {target_id} with {tool_id}", "unlock {target_id}"),
        examples=("unlock burrow door with brass key",),
    ),
    define_action(
        "hold",
        ("item_id",),
        tool_name="hold",
        patterns=("hold {item_id}", "equip {item_id}"),
    ),
    define_action(
        "unhold",
        ("item_id",),
        tool_name="unhold",
        patterns=("unhold {item_id}", "unequip {item_id}"),
    ),
    define_action("wear", ("item_id",), tool_name="wear", patterns=("wear {item_id}",)),
    define_action("remove", ("item_id",), tool_name="remove", patterns=("remove {item_id}",)),
    define_action(
        "use",
        ("item_id", "target_id", "tool_id"),
        tool_name="use",
        patterns=(
            "use {item_id}",
            "use {item_id} on {target_id}",
            "use {item_id} with {target_id}",
        ),
    ),
    define_action(
        "write",
        ("target_id", "text"),
        tool_name="write",
        cost=SPEECH_COST,
        patterns=("write {text} on {target_id}",),
    ),
    define_action(
        "sleep", tool_name="sleep", cost=FREE_COST, patterns=(ActionPattern("sleep", {}),)
    ),
    define_action("wake", tool_name="wake", cost=FREE_COST, patterns=(ActionPattern("wake", {}),)),
    define_action(
        "wait",
        tool_name="wait",
        cost=FREE_COST,
        patterns=(ActionPattern("wait", {}), ActionPattern("yield", {})),
        examples=("wait",),
    ),
    define_action(
        "say",
        ("text", "intent", "approach"),
        tool_name="say",
        cost=SPEECH_COST,
        required=("text",),
        patterns=("say {text}",),
    ),
    define_action(
        "tell",
        ("target_id", "text", "intent", "approach", "audible"),
        tool_name="tell",
        cost=SPEECH_COST,
        required=("target_id", "text"),
        patterns=("tell {target_id:word} {text}",),
    ),
    define_action(
        "start-conversation",
        ("target_ids", "topic", "timeout_seconds"),
        tool_name="start_conversation",
        lane=Lane.FOCUS,
        cost=FOCUS_COST,
        patterns=("start conversation with {target_ids}",),
    ),
    define_action(
        "conversation-line",
        ("conversation_id", "text", "intent", "approach"),
        tool_name="conversation_line",
        lane=Lane.FOCUS,
        cost=FOCUS_COST,
    ),
    define_action(
        "end-conversation",
        ("conversation_id", "reason"),
        tool_name="end_conversation",
        lane=Lane.FOCUS,
        cost=FOCUS_COST,
    ),
)

__all__ = ["ACTION_DEFINITIONS"]
