"""colonysim generation contribution compatibility surface."""

from ...worldgen.enrichment import ColonyWorldgenHook, ComponentPlanEnricher

CAPABILITIES = (
    "bunnyland.colonysim.allowed-area",
    "bunnyland.colonysim.bed-rest",
    "bunnyland.colonysim.body-part",
    "bunnyland.colonysim.captive",
    "bunnyland.colonysim.caravan",
    "bunnyland.colonysim.colony-wealth",
    "bunnyland.colonysim.faction-relation",
    "bunnyland.colonysim.forbidden",
    "bunnyland.colonysim.haulable",
    "bunnyland.colonysim.incident",
    "bunnyland.colonysim.infection",
    "bunnyland.colonysim.job",
    "bunnyland.colonysim.job-bill",
    "bunnyland.colonysim.medical-bed",
    "bunnyland.colonysim.medicine",
    "bunnyland.colonysim.mental-state",
    "bunnyland.colonysim.pawn-profile",
    "bunnyland.colonysim.prisoner",
    "bunnyland.colonysim.prosthetic",
    "bunnyland.colonysim.recipe",
    "bunnyland.colonysim.research",
    "bunnyland.colonysim.resource-node",
    "bunnyland.colonysim.resource-stack",
    "bunnyland.colonysim.room-quality",
    "bunnyland.colonysim.room-role",
    "bunnyland.colonysim.room-stat",
    "bunnyland.colonysim.stockpile",
    "bunnyland.colonysim.storage-filter",
    "bunnyland.colonysim.surgery",
    "bunnyland.colonysim.tech-unlock",
    "bunnyland.colonysim.trade-offer",
    "bunnyland.colonysim.work-capability",
    "bunnyland.colonysim.work-priority",
    "bunnyland.colonysim.workstation",
)
ALIASES = {
    "allowed-area": "bunnyland.colonysim.allowed-area",
    "bed-rest": "bunnyland.colonysim.bed-rest",
    "body-part": "bunnyland.colonysim.body-part",
    "captive": "bunnyland.colonysim.captive",
    "caravan": "bunnyland.colonysim.caravan",
    "colony-wealth": "bunnyland.colonysim.colony-wealth",
    "faction-relation": "bunnyland.colonysim.faction-relation",
    "forbidden": "bunnyland.colonysim.forbidden",
    "haulable": "bunnyland.colonysim.haulable",
    "incident": "bunnyland.colonysim.incident",
    "infection": "bunnyland.colonysim.infection",
    "job": "bunnyland.colonysim.job",
    "job-bill": "bunnyland.colonysim.job-bill",
    "medical-bed": "bunnyland.colonysim.medical-bed",
    "medicine": "bunnyland.colonysim.medicine",
    "mental-state": "bunnyland.colonysim.mental-state",
    "pawn-profile": "bunnyland.colonysim.pawn-profile",
    "prisoner": "bunnyland.colonysim.prisoner",
    "prosthetic": "bunnyland.colonysim.prosthetic",
    "recipe": "bunnyland.colonysim.recipe",
    "research": "bunnyland.colonysim.research",
    "resource-node": "bunnyland.colonysim.resource-node",
    "resource-stack": "bunnyland.colonysim.resource-stack",
    "room-quality": "bunnyland.colonysim.room-quality",
    "room-role": "bunnyland.colonysim.room-role",
    "room-stat": "bunnyland.colonysim.room-stat",
    "stockpile": "bunnyland.colonysim.stockpile",
    "storage-filter": "bunnyland.colonysim.storage-filter",
    "surgery": "bunnyland.colonysim.surgery",
    "tech-unlock": "bunnyland.colonysim.tech-unlock",
    "trade-offer": "bunnyland.colonysim.trade-offer",
    "work-capability": "bunnyland.colonysim.work-capability",
    "work-priority": "bunnyland.colonysim.work-priority",
    "workstation": "bunnyland.colonysim.workstation",
}
GENERATION_ENRICHER = ComponentPlanEnricher(ColonyWorldgenHook, provided_capabilities=CAPABILITIES)

__all__ = ["GENERATION_ENRICHER", "ColonyWorldgenHook"]
