"""Canonical Colony Sim plugin entrypoint."""

from bunnyland.simpacks.colonysim.mechanics import (
    AllowedIn,
    AllowItemHandler,
    AssignedTo,
    AssignJobHandler,
    BakeHandler,
    BedRestComponent,
    BodyPartHealthComponent,
    CaravanComponent,
    CaravanFormedEvent,
    ClaimOwnershipHandler,
    ColonyIncidentComponent,
    ColonyIncidentResolvedEvent,
    ColonySimComponent,
    ColonyWealthComponent,
    CompleteJobHandler,
    CompleteTradeHandler,
    CraftHandler,
    CreateStockpileHandler,
    FactionRelationComponent,
    ForbiddenComponent,
    ForbidItemHandler,
    FormCaravanHandler,
    GatherResourceHandler,
    HasBodyPart,
    HaulableComponent,
    HaulItemHandler,
    InfectionComponent,
    JobBillComponent,
    JobBillProgressedEvent,
    JobComponent,
    MedicalBedComponent,
    MedicineComponent,
    MemberOfCaravan,
    MentalStateComponent,
    MergeStackHandler,
    Owns,
    PawnProfileComponent,
    PawnProfileUpdatedEvent,
    PerformSurgeryHandler,
    PrisonerComponent,
    PrisonerPolicySetEvent,
    ProgressJobBillHandler,
    ProstheticComponent,
    RecipeComponent,
    RecruitmentProgressedEvent,
    RecruitPrisonerHandler,
    ReleaseOwnershipHandler,
    ReleaseReservationHandler,
    RescueToBedHandler,
    ResearchProgressedEvent,
    ResearchProjectComponent,
    ResearchProjectHandler,
    ReservedBy,
    ReserveHandler,
    ResolveColonyIncidentHandler,
    ResourceNodeComponent,
    ResourceRegenSystem,
    ResourceStackComponent,
    RoomQualityComponent,
    RoomRoleComponent,
    RoomStatComponent,
    SetAllowedAreaHandler,
    SetPrisonerPolicyHandler,
    SetStorageFilterHandler,
    SetWorkPriorityHandler,
    SplitStackHandler,
    StockpileComponent,
    StorageFilterComponent,
    SurgeryBillComponent,
    SurgeryPerformedEvent,
    TechUnlockComponent,
    TechUnlockedEvent,
    TendWoundHandler,
    TradeCompletedEvent,
    TradeOfferComponent,
    UpdatePawnProfileHandler,
    WorkCapabilityComponent,
    WorkPriorityComponent,
    WorkstationComponent,
    colonysim_fragments,
    install_colonysim,
)

from ...plugins.ids import (
    COLONYSIM,
    CORE_VERBS,
    LIFESIM,
)
from ...plugins.model import (
    CommandContribution,
    ContentContribution,
    DependencyContribution,
    EcsContribution,
    Plugin,
    PluginPlacement,
    RuntimeContribution,
)
from .actions import ACTION_DEFINITIONS
from .demos import COLONYSIM_DEMO
from .generation import CAPABILITIES, GENERATION_ENRICHER
from .resolution import RESOLUTION_RULES


def _definition() -> Plugin:
    return Plugin(
        id=COLONYSIM,
        name="Colony Sim",
        dependencies=DependencyContribution(requires=(CORE_VERBS, LIFESIM)),
        ecs=EcsContribution(
            components=(
                ColonySimComponent,
                ResourceNodeComponent,
                ResourceStackComponent,
                StockpileComponent,
                StorageFilterComponent,
                HaulableComponent,
                ForbiddenComponent,
                WorkstationComponent,
                RecipeComponent,
                JobComponent,
                JobBillComponent,
                WorkPriorityComponent,
                WorkCapabilityComponent,
                PawnProfileComponent,
                RoomRoleComponent,
                RoomStatComponent,
                RoomQualityComponent,
                ColonyWealthComponent,
                PrisonerComponent,
                ResearchProjectComponent,
                TechUnlockComponent,
                ColonyIncidentComponent,
                FactionRelationComponent,
                TradeOfferComponent,
                CaravanComponent,
                MedicineComponent,
                MedicalBedComponent,
                BedRestComponent,
                InfectionComponent,
                BodyPartHealthComponent,
                SurgeryBillComponent,
                ProstheticComponent,
                MentalStateComponent,
            ),
            edges=(ReservedBy, AssignedTo, Owns, HasBodyPart, AllowedIn, MemberOfCaravan),
            systems=(ResourceRegenSystem,),
        ),
        commands=CommandContribution(
            action_definitions=ACTION_DEFINITIONS,
            action_handlers=(
                ReserveHandler,
                ReleaseReservationHandler,
                GatherResourceHandler,
                CreateStockpileHandler,
                SetStorageFilterHandler,
                ForbidItemHandler,
                AllowItemHandler,
                HaulItemHandler,
                SplitStackHandler,
                MergeStackHandler,
                CraftHandler,
                BakeHandler,
                SetWorkPriorityHandler,
                SetAllowedAreaHandler,
                UpdatePawnProfileHandler,
                ProgressJobBillHandler,
                SetPrisonerPolicyHandler,
                RecruitPrisonerHandler,
                ResearchProjectHandler,
                ResolveColonyIncidentHandler,
                CompleteTradeHandler,
                FormCaravanHandler,
                PerformSurgeryHandler,
                TendWoundHandler,
                RescueToBedHandler,
                AssignJobHandler,
                CompleteJobHandler,
                ClaimOwnershipHandler,
                ReleaseOwnershipHandler,
            ),
            typed_events=(
                PawnProfileUpdatedEvent,
                JobBillProgressedEvent,
                PrisonerPolicySetEvent,
                RecruitmentProgressedEvent,
                ResearchProgressedEvent,
                TechUnlockedEvent,
                ColonyIncidentResolvedEvent,
                TradeCompletedEvent,
                CaravanFormedEvent,
                SurgeryPerformedEvent,
            ),
        ),
        content=ContentContribution(
            prompt_fragments=(colonysim_fragments,),
            generation_capabilities=CAPABILITIES,
            generation_enrichers=(GENERATION_ENRICHER,),
            incident_resolution_rules=RESOLUTION_RULES,
            world_generators=(COLONYSIM_DEMO,),
        ),
        runtime=RuntimeContribution(service_factories=(install_colonysim,)),
    )


def plugin() -> Plugin:
    return _definition().model_copy(update={"placement": PluginPlacement.INNER})


def bunnyland_plugins() -> list[Plugin]:
    return [plugin()]


__all__ = ["bunnyland_plugins", "plugin"]
