"""Optional server API helpers for web clients.

The dependency-free pieces in this package expose world snapshots and event streams. The
FastAPI app factory is imported lazily by callers that install web-server dependencies.
"""

from .models import (
    CharacterProjectionResponse,
    CharacterQueuedCommandsResponse,
    CommandRequest,
    CommandResponse,
    DmProjectionResponse,
    DmRoomProjectionView,
    RecentEventsResponse,
    RoomProjectionResponse,
    WebControllerClaimRequest,
    WebControllerClaimResponse,
    WebControllerFallbackRequest,
    WebControllerFallbackResponse,
    WorldCharacterGenerationRequest,
    WorldCharacterGenerationResponse,
    WorldGenerateRequest,
    WorldGenerateResponse,
    WorldGenerationStatusResponse,
    WorldGeneratorInfo,
    WorldGeneratorListResponse,
    WorldItemGenerationRequest,
    WorldItemGenerationResponse,
    WorldLibraryResponse,
    WorldPatchRequest,
    WorldPatchResponse,
    WorldRoomGenerationRequest,
    WorldRoomGenerationResponse,
    WorldRuntimeResponse,
    WorldSaveResponse,
    WorldSchemaResponse,
)
from .serialization import (
    event_message,
    serialize_character_projection,
    serialize_character_queued_commands,
    serialize_dm_projection,
    serialize_event,
    serialize_room_projection,
    serialize_world,
)
from .subscriptions import EventStream, EventSubscription

__all__ = [
    "CommandRequest",
    "CommandResponse",
    "DmProjectionResponse",
    "DmRoomProjectionView",
    "CharacterProjectionResponse",
    "CharacterQueuedCommandsResponse",
    "EventStream",
    "EventSubscription",
    "RecentEventsResponse",
    "RoomProjectionResponse",
    "WebControllerFallbackRequest",
    "WebControllerFallbackResponse",
    "WebControllerClaimRequest",
    "WebControllerClaimResponse",
    "WorldCharacterGenerationRequest",
    "WorldCharacterGenerationResponse",
    "WorldGenerateRequest",
    "WorldGenerateResponse",
    "WorldGenerationStatusResponse",
    "WorldGeneratorInfo",
    "WorldGeneratorListResponse",
    "WorldItemGenerationRequest",
    "WorldItemGenerationResponse",
    "WorldLibraryResponse",
    "WorldPatchRequest",
    "WorldPatchResponse",
    "WorldRoomGenerationRequest",
    "WorldRoomGenerationResponse",
    "WorldRuntimeResponse",
    "WorldSaveResponse",
    "WorldSchemaResponse",
    "event_message",
    "serialize_character_queued_commands",
    "serialize_character_projection",
    "serialize_dm_projection",
    "serialize_event",
    "serialize_room_projection",
    "serialize_world",
]
