"""nukesim generation contribution compatibility surface."""

from ...worldgen.enrichment import LegacyWorldgenEnricher, NukeWorldgenHook

CAPABILITIES = (
    "bunnyland.nukesim.beacon",
    "bunnyland.nukesim.chem",
    "bunnyland.nukesim.chem-recipe",
    "bunnyland.nukesim.decontamination",
    "bunnyland.nukesim.faction-salvage",
    "bunnyland.nukesim.field-repair",
    "bunnyland.nukesim.generator",
    "bunnyland.nukesim.hotspot-marker",
    "bunnyland.nukesim.item-mod",
    "bunnyland.nukesim.junk",
    "bunnyland.nukesim.locked-crate",
    "bunnyland.nukesim.mutation",
    "bunnyland.nukesim.mutation-resistance",
    "bunnyland.nukesim.mutation-threshold",
    "bunnyland.nukesim.old-world-tech",
    "bunnyland.nukesim.rad-medicine",
    "bunnyland.nukesim.rad-protection",
    "bunnyland.nukesim.radiation-dose",
    "bunnyland.nukesim.radiation-source",
    "bunnyland.nukesim.raider-pressure",
    "bunnyland.nukesim.sample",
    "bunnyland.nukesim.scavenge-site",
    "bunnyland.nukesim.schematic",
    "bunnyland.nukesim.settlement",
    "bunnyland.nukesim.settlement-salvage",
    "bunnyland.nukesim.suppressant",
    "bunnyland.nukesim.tech-lead",
    "bunnyland.nukesim.terminal",
    "bunnyland.nukesim.trader-route",
    "bunnyland.nukesim.wasteland-artifact",
    "bunnyland.nukesim.water-purifier",
    "bunnyland.nukesim.water-purity",
)
ALIASES = {
    "beacon": "bunnyland.nukesim.beacon",
    "chem": "bunnyland.nukesim.chem",
    "chem-recipe": "bunnyland.nukesim.chem-recipe",
    "decontamination": "bunnyland.nukesim.decontamination",
    "faction-salvage": "bunnyland.nukesim.faction-salvage",
    "field-repair": "bunnyland.nukesim.field-repair",
    "generator": "bunnyland.nukesim.generator",
    "hotspot-marker": "bunnyland.nukesim.hotspot-marker",
    "item-mod": "bunnyland.nukesim.item-mod",
    "junk": "bunnyland.nukesim.junk",
    "locked-crate": "bunnyland.nukesim.locked-crate",
    "mutation": "bunnyland.nukesim.mutation",
    "mutation-resistance": "bunnyland.nukesim.mutation-resistance",
    "mutation-threshold": "bunnyland.nukesim.mutation-threshold",
    "old-world-tech": "bunnyland.nukesim.old-world-tech",
    "rad-medicine": "bunnyland.nukesim.rad-medicine",
    "rad-protection": "bunnyland.nukesim.rad-protection",
    "radiation-dose": "bunnyland.nukesim.radiation-dose",
    "radiation-source": "bunnyland.nukesim.radiation-source",
    "raider-pressure": "bunnyland.nukesim.raider-pressure",
    "sample": "bunnyland.nukesim.sample",
    "scavenge-site": "bunnyland.nukesim.scavenge-site",
    "schematic": "bunnyland.nukesim.schematic",
    "settlement": "bunnyland.nukesim.settlement",
    "settlement-salvage": "bunnyland.nukesim.settlement-salvage",
    "suppressant": "bunnyland.nukesim.suppressant",
    "tech-lead": "bunnyland.nukesim.tech-lead",
    "terminal": "bunnyland.nukesim.terminal",
    "trader-route": "bunnyland.nukesim.trader-route",
    "wasteland-artifact": "bunnyland.nukesim.wasteland-artifact",
    "water-purifier": "bunnyland.nukesim.water-purifier",
    "water-purity": "bunnyland.nukesim.water-purity",
}
GENERATION_ENRICHER = LegacyWorldgenEnricher(NukeWorldgenHook, provided_capabilities=CAPABILITIES)

__all__ = ["GENERATION_ENRICHER", "NukeWorldgenHook"]
