"""Canonical Life Sim plugin entrypoint."""

from bunnyland.foundation.affect.mechanics import AffectAggregation, AffectReactor
from bunnyland.foundation.consumables.actions import (
    DrinkHandler,
    EatHandler,
)
from bunnyland.foundation.consumables.components import (
    ConsumableComponent,
    DrinkableComponent,
    FoodComponent,
)
from bunnyland.foundation.needs.mechanics import (
    BatheHandler,
    CleanSelfHandler,
    ComfortNeedComponent,
    ComfortNeedSystem,
    DailyNeedChangedEvent,
    DailyNeedRecoveredEvent,
    FatigueComponent,
    FatigueSystem,
    FunNeedComponent,
    FunNeedSystem,
    HungerComponent,
    HungerSystem,
    HygieneComponent,
    HygieneSystem,
    NeedAffordanceComponent,
    PlayHandler,
    PrivacyNeedComponent,
    PrivacyNeedSystem,
    RelaxHandler,
    SafetyNeedComponent,
    SafetyNeedSystem,
    SeekPrivacyHandler,
    SeekSafetyHandler,
    SocialNeedComponent,
    SocialNeedSystem,
    ThirstComponent,
    ThirstSystem,
    need_fragments,
)
from bunnyland.simpacks.lifesim.mechanics import (
    AddWhimHandler,
    AdoptChildHandler,
    AgeComponent,
    AspirationChosenEvent,
    AspirationComponent,
    AssessTaxHandler,
    BillComponent,
    BillCreatedEvent,
    BillPaidEvent,
    BirthDueComponent,
    BusinessOpenedEvent,
    BusinessOwnerComponent,
    BusinessPromotedEvent,
    BusinessPurchaseEvent,
    BusinessSaleEvent,
    BuyItemHandler,
    CareerComponent,
    CareerStartedEvent,
    CharacterProfileComponent,
    ChargeRentHandler,
    ChooseAspirationHandler,
    ClaimHomeHandler,
    ClaimRoomHandler,
    CompleteMilestoneHandler,
    CompleteWhimHandler,
    ConfigureAgingHandler,
    CustomerComponent,
    EndPartnershipHandler,
    FindJobHandler,
    GossipSpreadEvent,
    GoToWorkHandler,
    HasBill,
    HasRoutine,
    HasWhim,
    HomeClaimedEvent,
    HomeComponent,
    HomeObjectComponent,
    HomeObjectMaintainedEvent,
    HomeObjectUsedEvent,
    HomeRestComponent,
    HouseholdComponent,
    HouseholdFundsComponent,
    HouseholdJoinedEvent,
    InheritanceRecordComponent,
    InheritedFrom,
    InvitationSentEvent,
    InviteOverHandler,
    JealousOf,
    JealousyTriggeredEvent,
    JobScheduleComponent,
    JoinHouseholdHandler,
    LifesimAgingPolicyChangedEvent,
    LifesimAgingPolicyComponent,
    LifeStageComponent,
    MaintainHomeObjectHandler,
    MentorshipCompletedEvent,
    MentorSkillHandler,
    MilestoneCompletedEvent,
    MilestoneComponent,
    OpenBusinessHandler,
    OwnsBusiness,
    ParentOf,
    PartnerOf,
    PayBillHandler,
    PayWageHandler,
    PracticeSkillHandler,
    PregnancyComponent,
    ProfileUpdatedEvent,
    PromoteBusinessHandler,
    PromotionEarnedEvent,
    QuitJobHandler,
    RelationshipStatus,
    RelationshipStatusChangedEvent,
    RentChargedEvent,
    ReproductiveComponent,
    ReputationComponent,
    ResolveBirthHandler,
    RoomClaimComponent,
    RoomClaimedEvent,
    RoutineComponent,
    RoutineDueEvent,
    RoutineSetEvent,
    SellItemHandler,
    SetRelationshipStatusHandler,
    SetRoutineHandler,
    SkillLeveledEvent,
    SkillSetComponent,
    SkillXPChangedEvent,
    SpreadGossipHandler,
    StartPartnershipHandler,
    StartPregnancyHandler,
    StudySkillHandler,
    TaxAssessedEvent,
    UpdateProfileHandler,
    UseHomeObjectHandler,
    WagePaidEvent,
    WellRestedComponent,
    WellRestedEvent,
    WhimAddedEvent,
    WhimCompletedEvent,
    WhimComponent,
    WitnessRomanceHandler,
    WorkShiftCompletedEvent,
    install_lifesim,
    lifesim_fragments,
)

from ...plugins.ids import (
    CORE_VERBS,
    LIFESIM,
)
from ...plugins.model import (
    CommandContribution,
    ContentContribution,
    DependencyContribution,
    EcsContribution,
    Plugin,
    PluginPlacement,
    RuntimeContribution,
)
from ...worldgen.apartment import APARTMENT_DEMO
from .actions import ACTION_DEFINITIONS
from .demos import (
    LIFESIM_DEMO,
    MIDNIGHT_BURGER_DEMO,
    MIDNIGHT_LAUNDROMAT_DEMO,
    VACANCY_MOTEL_DEMO,
)
from .generation import ALIASES, CAPABILITIES, GENERATION_ENRICHER


def _install_affect(actor) -> None:
    reactor = AffectReactor(actor.world)
    reactor.subscribe(actor.bus)
    actor.register_consequence(AffectAggregation())


def _definition() -> Plugin:
    return Plugin(
        id=LIFESIM,
        name="Life Sim",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(
            components=(
                HungerComponent,
                ThirstComponent,
                FatigueComponent,
                HygieneComponent,
                ComfortNeedComponent,
                FunNeedComponent,
                SocialNeedComponent,
                PrivacyNeedComponent,
                SafetyNeedComponent,
                NeedAffordanceComponent,
                FoodComponent,
                DrinkableComponent,
                ConsumableComponent,
                AspirationComponent,
                MilestoneComponent,
                HouseholdFundsComponent,
                BillComponent,
                CareerComponent,
                JobScheduleComponent,
                BusinessOwnerComponent,
                CustomerComponent,
                HouseholdComponent,
                HomeComponent,
                RoomClaimComponent,
                InheritanceRecordComponent,
                HomeRestComponent,
                WellRestedComponent,
                RoutineComponent,
                ReputationComponent,
                SkillSetComponent,
                CharacterProfileComponent,
                WhimComponent,
                HomeObjectComponent,
                AgeComponent,
                LifeStageComponent,
                LifesimAgingPolicyComponent,
                ReproductiveComponent,
                PregnancyComponent,
                BirthDueComponent,
            ),
            edges=(
                ParentOf,
                HasRoutine,
                HasBill,
                HasWhim,
                OwnsBusiness,
                PartnerOf,
                RelationshipStatus,
                JealousOf,
                InheritedFrom,
            ),
            systems=(
                HungerSystem,
                ThirstSystem,
                FatigueSystem,
                HygieneSystem,
                ComfortNeedSystem,
                FunNeedSystem,
                SocialNeedSystem,
                PrivacyNeedSystem,
                SafetyNeedSystem,
            ),
        ),
        commands=CommandContribution(
            action_definitions=ACTION_DEFINITIONS,
            action_handlers=(
                EatHandler,
                DrinkHandler,
                BatheHandler,
                CleanSelfHandler,
                PlayHandler,
                RelaxHandler,
                SeekPrivacyHandler,
                SeekSafetyHandler,
                ChooseAspirationHandler,
                CompleteMilestoneHandler,
                PracticeSkillHandler,
                StudySkillHandler,
                MentorSkillHandler,
                UpdateProfileHandler,
                AddWhimHandler,
                CompleteWhimHandler,
                UseHomeObjectHandler,
                MaintainHomeObjectHandler,
                InviteOverHandler,
                ConfigureAgingHandler,
                FindJobHandler,
                GoToWorkHandler,
                QuitJobHandler,
                PayWageHandler,
                AssessTaxHandler,
                ChargeRentHandler,
                PayBillHandler,
                OpenBusinessHandler,
                BuyItemHandler,
                SellItemHandler,
                PromoteBusinessHandler,
                JoinHouseholdHandler,
                ClaimHomeHandler,
                ClaimRoomHandler,
                SetRoutineHandler,
                SetRelationshipStatusHandler,
                SpreadGossipHandler,
                WitnessRomanceHandler,
                StartPartnershipHandler,
                EndPartnershipHandler,
                StartPregnancyHandler,
                ResolveBirthHandler,
                AdoptChildHandler,
            ),
            typed_events=(
                AspirationChosenEvent,
                MilestoneCompletedEvent,
                SkillXPChangedEvent,
                SkillLeveledEvent,
                MentorshipCompletedEvent,
                ProfileUpdatedEvent,
                WhimAddedEvent,
                WhimCompletedEvent,
                HomeObjectUsedEvent,
                HomeObjectMaintainedEvent,
                InvitationSentEvent,
                LifesimAgingPolicyChangedEvent,
                CareerStartedEvent,
                WorkShiftCompletedEvent,
                WagePaidEvent,
                BillCreatedEvent,
                TaxAssessedEvent,
                RentChargedEvent,
                BillPaidEvent,
                PromotionEarnedEvent,
                BusinessOpenedEvent,
                BusinessPurchaseEvent,
                BusinessSaleEvent,
                BusinessPromotedEvent,
                HouseholdJoinedEvent,
                HomeClaimedEvent,
                RoomClaimedEvent,
                WellRestedEvent,
                RoutineSetEvent,
                RoutineDueEvent,
                RelationshipStatusChangedEvent,
                GossipSpreadEvent,
                JealousyTriggeredEvent,
                DailyNeedChangedEvent,
                DailyNeedRecoveredEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(_install_affect, install_lifesim)),
        content=ContentContribution(
            prompt_fragments=(need_fragments, lifesim_fragments),
            generation_capabilities=CAPABILITIES,
            generation_aliases=ALIASES,
            generation_enrichers=(GENERATION_ENRICHER,),
            world_generators=(
                LIFESIM_DEMO,
                MIDNIGHT_BURGER_DEMO,
                VACANCY_MOTEL_DEMO,
                MIDNIGHT_LAUNDROMAT_DEMO,
                APARTMENT_DEMO,
            ),
        ),
    )


def plugin() -> Plugin:
    return _definition().model_copy(update={"placement": PluginPlacement.INNER})


def bunnyland_plugins() -> list[Plugin]:
    return [plugin()]


__all__ = ["bunnyland_plugins", "plugin"]
