"""dinosim generation contribution compatibility surface."""

from ...worldgen.enrichment import DinoWorldgenHook, LegacyWorldgenEnricher

CAPABILITIES = (
    "bunnyland.dinosim.ancient-sample",
    "bunnyland.dinosim.apex-predator",
    "bunnyland.dinosim.armor-plate",
    "bunnyland.dinosim.bait",
    "bunnyland.dinosim.bone",
    "bunnyland.dinosim.charge",
    "bunnyland.dinosim.creature-attack",
    "bunnyland.dinosim.creature-need",
    "bunnyland.dinosim.creature-product",
    "bunnyland.dinosim.dinosaur",
    "bunnyland.dinosim.egg",
    "bunnyland.dinosim.enclosure",
    "bunnyland.dinosim.fossil",
    "bunnyland.dinosim.fossil-survey",
    "bunnyland.dinosim.herd",
    "bunnyland.dinosim.hide",
    "bunnyland.dinosim.kaiju",
    "bunnyland.dinosim.nest",
    "bunnyland.dinosim.roar",
    "bunnyland.dinosim.scent",
    "bunnyland.dinosim.territory",
    "bunnyland.dinosim.toxin",
    "bunnyland.dinosim.track",
    "bunnyland.dinosim.trample",
    "bunnyland.dinosim.tranquilizer",
    "bunnyland.dinosim.water-creature",
    "bunnyland.dinosim.weak-point",
)
ALIASES = {
    "ancient-sample": "bunnyland.dinosim.ancient-sample",
    "apex-predator": "bunnyland.dinosim.apex-predator",
    "armor-plate": "bunnyland.dinosim.armor-plate",
    "bait": "bunnyland.dinosim.bait",
    "bone": "bunnyland.dinosim.bone",
    "charge": "bunnyland.dinosim.charge",
    "creature-attack": "bunnyland.dinosim.creature-attack",
    "creature-need": "bunnyland.dinosim.creature-need",
    "creature-product": "bunnyland.dinosim.creature-product",
    "dinosaur": "bunnyland.dinosim.dinosaur",
    "egg": "bunnyland.dinosim.egg",
    "enclosure": "bunnyland.dinosim.enclosure",
    "fossil": "bunnyland.dinosim.fossil",
    "fossil-survey": "bunnyland.dinosim.fossil-survey",
    "herd": "bunnyland.dinosim.herd",
    "hide": "bunnyland.dinosim.hide",
    "kaiju": "bunnyland.dinosim.kaiju",
    "nest": "bunnyland.dinosim.nest",
    "roar": "bunnyland.dinosim.roar",
    "scent": "bunnyland.dinosim.scent",
    "territory": "bunnyland.dinosim.territory",
    "toxin": "bunnyland.dinosim.toxin",
    "track": "bunnyland.dinosim.track",
    "trample": "bunnyland.dinosim.trample",
    "tranquilizer": "bunnyland.dinosim.tranquilizer",
    "water-creature": "bunnyland.dinosim.water-creature",
    "weak-point": "bunnyland.dinosim.weak-point",
}
GENERATION_ENRICHER = LegacyWorldgenEnricher(DinoWorldgenHook, provided_capabilities=CAPABILITIES)

__all__ = ["GENERATION_ENRICHER", "DinoWorldgenHook"]
