"""Builtin bunnyland plugins (spec 21.4): core verbs, lifesim, memory.

This module is a plugin source: ``bunnyland_plugins()`` returns the plugins it declares,
exactly as a third-party module would. The world actor still provides the always-on
spine (clock, Action/Focus regen, downed/death); these plugins add the optional verb
surface and mechanics so disabling one removes its components/systems/verbs.
"""

from __future__ import annotations

from ..core.controllers import MCPControllerComponent
from ..core.handlers import (
    MoveHandler,
    PutHandler,
    SayHandler,
    SleepHandler,
    TakeHandler,
    TellHandler,
    UseHandler,
    WaitHandler,
    WakeHandler,
    WriteHandler,
)
from ..mechanics.affect import AffectAggregation, AffectReactor
from ..mechanics.barbariansim import (
    ArmorComponent,
    AttackHandler,
    ChallengeHandler,
    CharacterPoisonedEvent,
    CleanseCorruptionHandler,
    CorruptionCleansedEvent,
    CorruptionComponent,
    CorruptionGainedEvent,
    DefendHandler,
    DefendingComponent,
    DurabilityComponent,
    ExposureChangedEvent,
    ExposureDamageEvent,
    FortificationComponent,
    FortifyHandler,
    FrostbiteStartedEvent,
    GainCorruptionHandler,
    HeatstrokeStartedEvent,
    ItemBrokenEvent,
    ItemDamagedEvent,
    ItemRepairedEvent,
    PickpocketHandler,
    PoisonCharacterHandler,
    PoisonComponent,
    PoisonProgressedEvent,
    PoisonTreatedEvent,
    RaidHandler,
    RepairItemHandler,
    ShelterComponent,
    SparHandler,
    StaminaChangedEvent,
    StaminaComponent,
    TemperatureExposureComponent,
    TemperatureResistanceComponent,
    TreatPoisonHandler,
    WeaponComponent,
    barbariansim_fragments,
    install_barbariansim,
)
from ..mechanics.colonysim import (
    AssignedTo,
    AssignJobHandler,
    ClaimOwnershipHandler,
    ColonySimComponent,
    CompleteJobHandler,
    CraftHandler,
    GatherResourceHandler,
    JobComponent,
    Owns,
    RecipeComponent,
    ReleaseOwnershipHandler,
    ReleaseReservationHandler,
    ReservedBy,
    ReserveHandler,
    ResourceNodeComponent,
    ResourceRegenSystem,
    ResourceStackComponent,
    WorkstationComponent,
    colonysim_fragments,
    install_colonysim,
)
from ..mechanics.consumables import ConsumableComponent, DrinkableComponent, FoodComponent
from ..mechanics.daggersim import (
    AcceptGeneratedQuestHandler,
    AccountOpenedEvent,
    AfflictionContractedEvent,
    AskForWorkHandler,
    AskRumorHandler,
    AttemptPacifyHandler,
    AutomapComponent,
    BankAccountComponent,
    BankComponent,
    BountyComponent,
    BountyPostedEvent,
    CastSpellHandler,
    ClassTemplateComponent,
    CommitCrimeHandler,
    CompleteGeneratedQuestHandler,
    ContractAfflictionHandler,
    ConversationToneComponent,
    CreateCustomClassHandler,
    CreateSpellHandler,
    CreatureLanguageComponent,
    CreaturePacifiedEvent,
    CrimeCommittedEvent,
    CrimeRecordComponent,
    CustomClassComponent,
    CustomClassCreatedEvent,
    CustomSpellComponent,
    DaggerQuestRewardComponent,
    DebtComponent,
    DepositHandler,
    DepositMadeEvent,
    DialogueApproachComponent,
    DungeonComponent,
    DungeonEnteredEvent,
    DungeonExitedEvent,
    DungeonGeneratedEvent,
    DungeonObjectiveComponent,
    DungeonObjectiveFoundEvent,
    DungeonRequestedEvent,
    DungeonRoomComponent,
    DungeonRoomDiscoveredEvent,
    EnchantedItemComponent,
    EnchantItemHandler,
    EnterDungeonHandler,
    EtiquetteSkillComponent,
    ExpandSiteHandler,
    ExpansionHookComponent,
    ExpansionRequestedEvent,
    FeedingNeedChangedEvent,
    FeedingNeedComponent,
    FinePaidEvent,
    GeneratedQuestComponent,
    GeneratedSiteInstantiatedEvent,
    HostilityComponent,
    InstitutionComponent,
    InstitutionJoinedEvent,
    InstitutionServiceComponent,
    InstitutionServiceUsedEvent,
    InvestigateRumorHandler,
    ItemEnchantedEvent,
    JoinInstitutionHandler,
    LanguageSkillComponent,
    LawRegionComponent,
    LeaveDungeonHandler,
    LoanComponent,
    LoanDefaultedEvent,
    LoanIssuedEvent,
    LoanRepaidEvent,
    MarkPathHandler,
    MemberOfInstitution,
    OpenBankAccountHandler,
    OpenSecretDoorHandler,
    PacificationAttemptedEvent,
    PacifiedComponent,
    PayFineHandler,
    PlanTravelHandler,
    ProceduralSiteComponent,
    QuestDeadlineComponent,
    QuestFailedEvent,
    QuestGeneratedEvent,
    QuestTemplateComponent,
    RecallAnchorComponent,
    RecallAnchorSetEvent,
    RecallUsedEvent,
    RepayLoanHandler,
    RequestDungeonHandler,
    RestHandler,
    RestRiskComponent,
    RumorBecameExpansionEvent,
    RumorComponent,
    RumorDisprovenEvent,
    RumorHeardEvent,
    RumorReliabilityComponent,
    RumorSourceComponent,
    RumorTargetComponent,
    RumorVerifiedEvent,
    SearchRoomHandler,
    SecretDoorComponent,
    SecretDoorFoundEvent,
    SetRecallHandler,
    SocialRegisterComponent,
    SpellCastEvent,
    SpellCreatedEvent,
    SpellTemplateComponent,
    StreetwiseSkillComponent,
    SupernaturalAfflictionComponent,
    TakeLoanHandler,
    TransformationStartedEvent,
    TransformHandler,
    TravelCompletedEvent,
    TravelHubComponent,
    TravelModeComponent,
    TravelPlanComponent,
    TravelRoute,
    TravelStartedEvent,
    UnrealizedLocationComponent,
    UseInstitutionServiceHandler,
    UseRecallHandler,
    ViewMapHandler,
    WereformComponent,
    WithdrawalMadeEvent,
    WithdrawHandler,
    daggersim_fragments,
    install_daggersim,
)
from ..mechanics.daggersim import (
    QuestAcceptedEvent as DaggerQuestAcceptedEvent,
)
from ..mechanics.daggersim import (
    QuestCompletedEvent as DaggerQuestCompletedEvent,
)
from ..mechanics.dinosim import (
    AncientSampleComponent,
    AncientSampleExtractedEvent,
    ApexPredatorAppearedEvent,
    ApexPredatorComponent,
    ApproachCreatureHandler,
    ArmorPlateComponent,
    ArmyCalledEvent,
    ArmyResponseComponent,
    AssignGuardHandler,
    AssignRanchWorkHandler,
    BaitComponent,
    BaitSetEvent,
    BoneComponent,
    BreachComponent,
    BuildEnclosureHandler,
    CallForHelpHandler,
    ChargeComponent,
    CloneCandidateComponent,
    ClonePreparedEvent,
    CollectEggHandler,
    CommandCompanionHandler,
    CommandComponent,
    CommandTrainedEvent,
    CompanionCommandedEvent,
    CompanionComponent,
    ContainmentProtocolComponent,
    ContainmentTriggeredEvent,
    CreatureAttackComponent,
    CreatureAttackedEvent,
    CreatureChargedEvent,
    CreatureEscapedEvent,
    CreatureMilkComponent,
    CreatureMountedEvent,
    CreatureProductCollectedEvent,
    CreatureProductComponent,
    CreatureRecalledEvent,
    CreatureRecapturedEvent,
    CreatureRoaredEvent,
    CreatureTamedEvent,
    CreatureTrackedEvent,
    CreatureTrampledEvent,
    CreatureTranquilizedEvent,
    DinosaurComponent,
    DinosimPolicyComponent,
    DodgeCreatureHandler,
    DriveOffPredatorHandler,
    EggComponent,
    EggFertilizedEvent,
    EggHatchedEvent,
    EggIncubatedEvent,
    EggLaidEvent,
    EnclosureBuiltEvent,
    EnclosureComponent,
    EscapeRiskComponent,
    EvacuateRoomHandler,
    ExtractAncientSampleHandler,
    FearComponent,
    FeedingPenComponent,
    FeedStockedEvent,
    FeedStoreComponent,
    FenceComponent,
    FenceRepairedEvent,
    FertilityComponent,
    FertilizeEggHandler,
    FightCreatureHandler,
    FossilFragmentComponent,
    FossilIdentifiedEvent,
    GateComponent,
    GateReinforcedEvent,
    GrappleComponent,
    GuardAnimalComponent,
    GuardAssignedEvent,
    GuardBehaviorComponent,
    HarvestProductHandler,
    HatchEggHandler,
    HatchlingComponent,
    HiddenFromCreatureEvent,
    HideComponent,
    HideFromCreatureHandler,
    HuntBehaviorComponent,
    IdentifyFossilHandler,
    IncubateEggHandler,
    IncubationComponent,
    KaijuArrivedEvent,
    KaijuComponent,
    LayEggHandler,
    LockPenHandler,
    MountComponent,
    MountCreatureHandler,
    OpenPenHandler,
    PackHuntComponent,
    PenLockedEvent,
    PenOpenedEvent,
    PredatorDrivenOffEvent,
    PrepareCloneHandler,
    QuarantinePenComponent,
    RanchLaborComponent,
    RanchWorkAssignedEvent,
    RecallComponent,
    RecallCreatureHandler,
    RecaptureCreatureHandler,
    ReinforceGateHandler,
    ReinforcementComponent,
    RepairDamageHandler,
    RepairFenceHandler,
    ReptileProcreationComponent,
    RoarComponent,
    RoomEvacuatedEvent,
    ScentComponent,
    SetBaitHandler,
    SettlementDamageComponent,
    SettlementDamagedEvent,
    SettlementDamageRepairedEvent,
    SignalArmyHandler,
    SpeciesComponent,
    SpeciesIdentificationComponent,
    StampedeComponent,
    StampedeStartedEvent,
    StockFeedHandler,
    TameCreatureHandler,
    TamingComponent,
    TamingProgressedEvent,
    TargetWeakPointHandler,
    ToxinComponent,
    TrackComponent,
    TrackCreatureHandler,
    TrainCommandHandler,
    TrainingComponent,
    TrampleComponent,
    TranquilizeCreatureHandler,
    TranquilizerComponent,
    TriggerContainmentHandler,
    TrustComponent,
    WeakPointComponent,
    WeakPointHitEvent,
    dinosim_fragments,
    install_dinosim,
)
from ..mechanics.dragonsim import (
    AcceptQuestHandler,
    CompleteObjectiveHandler,
    DiscoverLocationHandler,
    DiscoveryComponent,
    FactionComponent,
    FactionJoinedEvent,
    FactionLeftEvent,
    FactionReputationComponent,
    JoinFactionHandler,
    LeaveFactionHandler,
    LocationDiscoveredEvent,
    MemberOf,
    PointOfInterestComponent,
    QuestAcceptedEvent,
    QuestCompletedEvent,
    QuestComponent,
    QuestObjectiveCompletedEvent,
    QuestObjectiveComponent,
    QuestRewardComponent,
    QuestStageComponent,
    dragonsim_fragments,
)
from ..mechanics.eat_drink import DrinkHandler, EatHandler
from ..mechanics.environment import (
    CalendarComponent,
    ExtinguishHandler,
    FireComponent,
    FireDamageEvent,
    FireExtinguishedEvent,
    FireSpreadEvent,
    FireStartedEvent,
    FlammableComponent,
    IgniteHandler,
    TimeOfDayComponent,
    WeatherComponent,
    environment_fragments,
    install_environment,
)
from ..mechanics.gardensim import (
    CropComponent,
    CropGrewEvent,
    CropGrowthComponent,
    CropHarvestedEvent,
    CropReadyEvent,
    CropWateredEvent,
    CropWitheredEvent,
    FertilizeHandler,
    FertilizerAppliedEvent,
    FertilizerComponent,
    HarvestableComponent,
    HarvestCropHandler,
    PlantHandler,
    SeedComponent,
    SeedPlantedEvent,
    SoilComponent,
    SoilTilledEvent,
    TilledComponent,
    TillHandler,
    WaterCropHandler,
    WateredComponent,
    gardensim_fragments,
    install_gardensim,
)
from ..mechanics.lifesim import (
    AdoptChildHandler,
    AgeComponent,
    AspirationChosenEvent,
    AspirationComponent,
    AssessTaxHandler,
    BillComponent,
    BillCreatedEvent,
    BillPaidEvent,
    BirthDueComponent,
    BusinessOpenedEvent,
    BusinessOwnerComponent,
    BusinessPromotedEvent,
    BusinessPurchaseEvent,
    BusinessSaleEvent,
    BuyItemHandler,
    CareerComponent,
    CareerStartedEvent,
    ChargeRentHandler,
    ChooseAspirationHandler,
    ClaimHomeHandler,
    ClaimRoomHandler,
    CompleteMilestoneHandler,
    CustomerComponent,
    EndPartnershipHandler,
    FindJobHandler,
    GossipSpreadEvent,
    GoToWorkHandler,
    HasBill,
    HasRoutine,
    HomeClaimedEvent,
    HomeComponent,
    HomeRestComponent,
    HouseholdComponent,
    HouseholdFundsComponent,
    HouseholdJoinedEvent,
    JealousOf,
    JealousyTriggeredEvent,
    JobScheduleComponent,
    JoinHouseholdHandler,
    LifesimAgingPolicyComponent,
    LifeStageComponent,
    MentorshipCompletedEvent,
    MentorSkillHandler,
    MilestoneCompletedEvent,
    MilestoneComponent,
    OpenBusinessHandler,
    OwnsBusiness,
    ParentOf,
    PartnerOf,
    PayBillHandler,
    PayWageHandler,
    PracticeSkillHandler,
    PregnancyComponent,
    PromoteBusinessHandler,
    PromotionEarnedEvent,
    QuitJobHandler,
    RelationshipStatus,
    RelationshipStatusChangedEvent,
    RentChargedEvent,
    ReproductiveComponent,
    ReputationComponent,
    ResolveBirthHandler,
    RoomClaimComponent,
    RoomClaimedEvent,
    RoutineComponent,
    RoutineDueEvent,
    RoutineSetEvent,
    SellItemHandler,
    SetRelationshipStatusHandler,
    SetRoutineHandler,
    SkillLeveledEvent,
    SkillSetComponent,
    SkillXPChangedEvent,
    SpreadGossipHandler,
    StartPartnershipHandler,
    StartPregnancyHandler,
    StudySkillHandler,
    TaxAssessedEvent,
    WagePaidEvent,
    WellRestedComponent,
    WellRestedEvent,
    WitnessRomanceHandler,
    WorkShiftCompletedEvent,
    install_lifesim,
    lifesim_fragments,
)
from ..mechanics.mechanisms import install_mechanisms
from ..mechanics.needs import (
    HungerComponent,
    HungerSystem,
    ThirstComponent,
    ThirstSystem,
    need_fragments,
)
from ..mechanics.nukesim import (
    DecontaminateHandler,
    DecontaminationAppliedEvent,
    DecontaminationComponent,
    HazardTriggeredEvent,
    ItemScrappedEvent,
    JunkComponent,
    LootFoundEvent,
    LootTableComponent,
    MutationComponent,
    MutationManifestedEvent,
    MutationPressureChangedEvent,
    MutationResistanceComponent,
    MutationStabilizedEvent,
    MutationThresholdComponent,
    RadiationDoseComponent,
    RadiationExposureEvent,
    RadiationScannedEvent,
    RadiationSicknessChangedEvent,
    RadiationSicknessComponent,
    RadiationSourceComponent,
    RadiationSourceSealedEvent,
    RadMedicineComponent,
    RadMedicineUsedEvent,
    RadProtectionComponent,
    ScanRadiationHandler,
    ScavengeHandler,
    ScavengeSiteComponent,
    ScrapItemHandler,
    SealRadiationSourceHandler,
    SiteScavengedEvent,
    StabilizeMutationHandler,
    UseRadMedicineHandler,
    install_nukesim,
    nukesim_fragments,
)
from ..mechanics.persona import (
    GoalComponent,
    PreferenceComponent,
    TraitSetComponent,
    persona_fragments,
)
from ..mechanics.policy import (
    CharacterBoundaryComponent,
    WorldPolicyComponent,
    install_policy,
)
from ..mechanics.social import SocialBond, install_social, relationship_fragments
from ..mechanics.storyteller import (
    IncidentBudgetComponent,
    IncidentComponent,
    IncidentHistoryComponent,
    IncidentProposedEvent,
    IncidentResolvedEvent,
    IncidentStartedEvent,
    ResolveIncidentHandler,
    StorytellerComponent,
    ThreatPointsComponent,
    install_storyteller,
    storyteller_fragments,
)
from ..mechanics.toonsim import (
    MoveSpriteHandler,
    SpriteImage,
    SpriteLayer,
    SpriteMovedEvent,
    SpritePosition,
    SpriteScale,
    install_toonsim,
)
from ..mechanics.voidsim import (
    AirlockComponent,
    AirlockCycledEvent,
    AnswerDistressSignalHandler,
    AstrogationComponent,
    BulkheadComponent,
    ChaosInfluenceAppliedEvent,
    ChaosInfluenceComponent,
    ChaosMutationPressureComponent,
    ChaosWardComponent,
    CoursePlottedEvent,
    CyberneticMutationPressureComponent,
    CycleAirlockHandler,
    DistressSignalComponent,
    DockedTo,
    DockHandler,
    DockingCompletedEvent,
    EnterOrbitHandler,
    EvacuateModuleHandler,
    FuelChangedEvent,
    FuelComponent,
    HabitatModuleComponent,
    InspectShipSystemHandler,
    JumpCompletedEvent,
    JumpDriveComponent,
    JumpHandler,
    JumpRoute,
    JumpStartedEvent,
    LandHandler,
    LandingCompletedEvent,
    LaunchHandler,
    LeaveOrbitHandler,
    LifeSupportComponent,
    LifeSupportFailedEvent,
    ModuleEvacuatedEvent,
    NavigationHazardEncounteredEvent,
    NavigationRouteComponent,
    OpenAirlockHandler,
    OrbitalBodyComponent,
    OrbitComponent,
    OrbitEnteredEvent,
    OxygenComponent,
    PlotCourseHandler,
    PowerGridComponent,
    PowerReroutedEvent,
    PressureChangedEvent,
    PressurizedComponent,
    RadiationMutationPressureComponent,
    RadiationShieldComponent,
    RefuelHandler,
    RepairSystemHandler,
    ReroutePowerHandler,
    ScanHandler,
    SealBulkheadHandler,
    SensorComponent,
    ShipComponent,
    ShipSystemComponent,
    ShipSystemDamagedEvent,
    ShipSystemRepairedEvent,
    SignalDetectedEvent,
    StarSystemComponent,
    StationComponent,
    UndockHandler,
    install_voidsim,
    voidsim_fragments,
)
from ..memory import install_memory
from ..worldgen.apartment import APARTMENT_DEMO
from ..worldgen.examples import (
    BARBARIANSIM_DEMO,
    CLUE_SNACK_DEMO,
    COLONYSIM_DEMO,
    DAGGERSIM_DEMO,
    DINOSIM_DEMO,
    DIVE_SCHEME_DEMO,
    DRAGONSIM_DEMO,
    GARDENSIM_DEMO,
    GOTHIC_COUNT_DEMO,
    LIFESIM_DEMO,
    NUKESIM_DEMO,
    STAR_OPERA_DEMO,
    VOIDSIM_DEMO,
)
from ..worldgen.generators import (
    WorldGenerator,
    empty_generator,
    halloween_generator,
    holiday_generator,
    oneshot_generator,
    recursive_generator,
    tower_debate_generator,
    waiting_room_generator,
)
from .model import (
    CommandContribution,
    ContentContribution,
    DependencyContribution,
    EcsContribution,
    Plugin,
    RuntimeContribution,
)

CORE_VERBS = "bunnyland.core_verbs"
LIFESIM = "bunnyland.lifesim"
MEMORY = "bunnyland.memory"
WORLDGEN = "bunnyland.worldgen"
ENVIRONMENT = "bunnyland.environment"
MECHANISMS = "bunnyland.mechanisms"
SOCIAL = "bunnyland.social"
POLICY = "bunnyland.policy"
PERSONA = "bunnyland.persona"
COLONYSIM = "bunnyland.colonysim"
BARBARIANSIM = "bunnyland.barbariansim"
GARDENSIM = "bunnyland.gardensim"
DINOSIM = "bunnyland.dinosim"
DRAGONSIM = "bunnyland.dragonsim"
DAGGERSIM = "bunnyland.daggersim"
VOIDSIM = "bunnyland.voidsim"
NUKESIM = "bunnyland.nukesim"
TOONSIM = "bunnyland.toonsim"
STORYTELLER = "bunnyland.storyteller"
MCP = "bunnyland.mcp"


def _install_affect(actor) -> None:
    reactor = AffectReactor(actor.world)
    reactor.subscribe(actor.bus)
    actor.register_consequence(AffectAggregation())


def core_verbs_plugin() -> Plugin:
    return Plugin(
        id=CORE_VERBS,
        name="Core Verbs",
        commands=CommandContribution(
            action_handlers=(
                MoveHandler,
                TakeHandler,
                PutHandler,
                UseHandler,
                WriteHandler,
                SleepHandler,
                WakeHandler,
                WaitHandler,
                SayHandler,
                TellHandler,
            )
        ),
    )


def lifesim_plugin() -> Plugin:
    return Plugin(
        id=LIFESIM,
        name="Life Sim",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(
            components=(
                HungerComponent,
                ThirstComponent,
                FoodComponent,
                DrinkableComponent,
                ConsumableComponent,
                AspirationComponent,
                MilestoneComponent,
                HouseholdFundsComponent,
                BillComponent,
                CareerComponent,
                JobScheduleComponent,
                BusinessOwnerComponent,
                CustomerComponent,
                HouseholdComponent,
                HomeComponent,
                RoomClaimComponent,
                HomeRestComponent,
                WellRestedComponent,
                RoutineComponent,
                ReputationComponent,
                SkillSetComponent,
                AgeComponent,
                LifeStageComponent,
                LifesimAgingPolicyComponent,
                ReproductiveComponent,
                PregnancyComponent,
                BirthDueComponent,
            ),
            edges=(
                ParentOf,
                HasRoutine,
                HasBill,
                OwnsBusiness,
                PartnerOf,
                RelationshipStatus,
                JealousOf,
            ),
            systems=(HungerSystem, ThirstSystem),
        ),
        commands=CommandContribution(
            action_handlers=(
                EatHandler,
                DrinkHandler,
                ChooseAspirationHandler,
                CompleteMilestoneHandler,
                PracticeSkillHandler,
                StudySkillHandler,
                MentorSkillHandler,
                FindJobHandler,
                GoToWorkHandler,
                QuitJobHandler,
                PayWageHandler,
                AssessTaxHandler,
                ChargeRentHandler,
                PayBillHandler,
                OpenBusinessHandler,
                BuyItemHandler,
                SellItemHandler,
                PromoteBusinessHandler,
                JoinHouseholdHandler,
                ClaimHomeHandler,
                ClaimRoomHandler,
                SetRoutineHandler,
                SetRelationshipStatusHandler,
                SpreadGossipHandler,
                WitnessRomanceHandler,
                StartPartnershipHandler,
                EndPartnershipHandler,
                StartPregnancyHandler,
                ResolveBirthHandler,
                AdoptChildHandler,
            ),
            typed_events=(
                AspirationChosenEvent,
                MilestoneCompletedEvent,
                SkillXPChangedEvent,
                SkillLeveledEvent,
                MentorshipCompletedEvent,
                CareerStartedEvent,
                WorkShiftCompletedEvent,
                WagePaidEvent,
                BillCreatedEvent,
                TaxAssessedEvent,
                RentChargedEvent,
                BillPaidEvent,
                PromotionEarnedEvent,
                BusinessOpenedEvent,
                BusinessPurchaseEvent,
                BusinessSaleEvent,
                BusinessPromotedEvent,
                HouseholdJoinedEvent,
                HomeClaimedEvent,
                RoomClaimedEvent,
                WellRestedEvent,
                RoutineSetEvent,
                RoutineDueEvent,
                RelationshipStatusChangedEvent,
                GossipSpreadEvent,
                JealousyTriggeredEvent,
            )
        ),
        runtime=RuntimeContribution(service_factories=(_install_affect, install_lifesim)),
        content=ContentContribution(
            prompt_fragments=(need_fragments, lifesim_fragments),
            world_generators=(LIFESIM_DEMO, APARTMENT_DEMO),
        ),
    )


def memory_plugin() -> Plugin:
    return Plugin(
        id=MEMORY,
        name="Memory",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        runtime=RuntimeContribution(service_factories=(_memory_factory,)),
    )


def _memory_factory(actor) -> None:
    install_memory(actor)


def _environment_factory(actor) -> None:
    install_environment(actor)


def environment_plugin() -> Plugin:
    return Plugin(
        id=ENVIRONMENT,
        name="Environment",
        ecs=EcsContribution(
            components=(
                CalendarComponent,
                TimeOfDayComponent,
                WeatherComponent,
                FlammableComponent,
                FireComponent,
            )
        ),
        commands=CommandContribution(
            action_handlers=(IgniteHandler, ExtinguishHandler),
            typed_events=(
                FireStartedEvent,
                FireSpreadEvent,
                FireDamageEvent,
                FireExtinguishedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(_environment_factory,)),
        content=ContentContribution(prompt_fragments=(environment_fragments,)),
    )


def _mechanisms_factory(actor) -> None:
    install_mechanisms(actor)


def mechanisms_plugin() -> Plugin:
    return Plugin(
        id=MECHANISMS,
        name="Mechanisms",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        runtime=RuntimeContribution(service_factories=(_mechanisms_factory,)),
    )


def _social_factory(actor) -> None:
    install_social(actor)


def social_plugin() -> Plugin:
    return Plugin(
        id=SOCIAL,
        name="Social Bonds",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(edges=(SocialBond,)),
        runtime=RuntimeContribution(service_factories=(_social_factory,)),
        content=ContentContribution(prompt_fragments=(relationship_fragments,)),
    )


def _policy_factory(actor) -> None:
    install_policy(actor)


def policy_plugin() -> Plugin:
    return Plugin(
        id=POLICY,
        name="Policy & Boundaries",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(components=(WorldPolicyComponent, CharacterBoundaryComponent)),
        runtime=RuntimeContribution(service_factories=(_policy_factory,)),
    )


def persona_plugin() -> Plugin:
    return Plugin(
        id=PERSONA,
        name="Persona",
        ecs=EcsContribution(
            components=(TraitSetComponent, PreferenceComponent, GoalComponent)
        ),
        content=ContentContribution(prompt_fragments=(persona_fragments,)),
    )


def worldgen_plugin() -> Plugin:
    return Plugin(
        id=WORLDGEN,
        name="World Generators",
        content=ContentContribution(
            world_generators=(
                WorldGenerator(
                    "empty",
                    empty_generator,
                    "blank ECS world with only the world clock",
                    uses_seed=False,
                ),
                WorldGenerator(
                    "waiting-room",
                    waiting_room_generator,
                    "a single stark white room with one red chair",
                    uses_seed=False,
                ),
                WorldGenerator(
                    "halloween",
                    halloween_generator,
                    "a haunted autumn porch, foyer, and cellar with seasonal props",
                    uses_seed=False,
                ),
                WorldGenerator(
                    "holiday",
                    holiday_generator,
                    "a snowy holiday workshop, stable, and field with festive props",
                    uses_seed=False,
                ),
                WorldGenerator(
                    "tower-debate",
                    tower_debate_generator,
                    "a locked tower room where an angel and devil debate forever",
                    uses_seed=False,
                ),
                CLUE_SNACK_DEMO,
                DIVE_SCHEME_DEMO,
                STAR_OPERA_DEMO,
                GOTHIC_COUNT_DEMO,
                WorldGenerator(
                    "oneshot", oneshot_generator, "single LLM proposal, instantiated at once"
                ),
                WorldGenerator(
                    "recursive", recursive_generator, "breadth-first graph, grown room-by-room"
                ),
            )
        ),
    )


def colonysim_plugin() -> Plugin:
    return Plugin(
        id=COLONYSIM,
        name="Colony Sim",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(
            components=(
                ColonySimComponent,
                ResourceNodeComponent,
                ResourceStackComponent,
                WorkstationComponent,
                RecipeComponent,
                JobComponent,
            ),
            edges=(ReservedBy, AssignedTo, Owns),
            systems=(ResourceRegenSystem,),
        ),
        commands=CommandContribution(
            action_handlers=(
                ReserveHandler,
                ReleaseReservationHandler,
                GatherResourceHandler,
                CraftHandler,
                AssignJobHandler,
                CompleteJobHandler,
                ClaimOwnershipHandler,
                ReleaseOwnershipHandler,
            )
        ),
        content=ContentContribution(
            prompt_fragments=(colonysim_fragments,),
            world_generators=(COLONYSIM_DEMO,),
        ),
        runtime=RuntimeContribution(service_factories=(install_colonysim,)),
    )


def barbariansim_plugin() -> Plugin:
    return Plugin(
        id=BARBARIANSIM,
        name="Barbarian Sim",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(
            components=(
                WeaponComponent,
                ArmorComponent,
                PoisonComponent,
                CorruptionComponent,
                DefendingComponent,
                DurabilityComponent,
                FortificationComponent,
                StaminaComponent,
                TemperatureResistanceComponent,
                ShelterComponent,
                TemperatureExposureComponent,
            )
        ),
        commands=CommandContribution(
            action_handlers=(
                AttackHandler,
                SparHandler,
                DefendHandler,
                ChallengeHandler,
                FortifyHandler,
                RaidHandler,
                RepairItemHandler,
                PoisonCharacterHandler,
                TreatPoisonHandler,
                GainCorruptionHandler,
                CleanseCorruptionHandler,
                PickpocketHandler,
            ),
            typed_events=(
                StaminaChangedEvent,
                ExposureChangedEvent,
                HeatstrokeStartedEvent,
                FrostbiteStartedEvent,
                ExposureDamageEvent,
                ItemDamagedEvent,
                ItemBrokenEvent,
                ItemRepairedEvent,
                CharacterPoisonedEvent,
                PoisonProgressedEvent,
                PoisonTreatedEvent,
                CorruptionGainedEvent,
                CorruptionCleansedEvent,
            )
        ),
        runtime=RuntimeContribution(service_factories=(install_barbariansim,)),
        content=ContentContribution(
            prompt_fragments=(barbariansim_fragments,),
            world_generators=(BARBARIANSIM_DEMO,),
        ),
    )


def gardensim_plugin() -> Plugin:
    return Plugin(
        id=GARDENSIM,
        name="Garden Sim",
        dependencies=DependencyContribution(
            requires=(CORE_VERBS,),
            recommends=(ENVIRONMENT, COLONYSIM),
        ),
        ecs=EcsContribution(
            components=(
                SoilComponent,
                TilledComponent,
                WateredComponent,
                FertilizerComponent,
                SeedComponent,
                CropComponent,
                CropGrowthComponent,
                HarvestableComponent,
            )
        ),
        commands=CommandContribution(
            action_handlers=(
                TillHandler,
                PlantHandler,
                WaterCropHandler,
                FertilizeHandler,
                HarvestCropHandler,
            ),
            typed_events=(
                SoilTilledEvent,
                SeedPlantedEvent,
                CropWateredEvent,
                FertilizerAppliedEvent,
                CropGrewEvent,
                CropReadyEvent,
                CropWitheredEvent,
                CropHarvestedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(install_gardensim,)),
        content=ContentContribution(
            prompt_fragments=(gardensim_fragments,),
            world_generators=(GARDENSIM_DEMO,),
        ),
    )


def dinosim_plugin() -> Plugin:
    return Plugin(
        id=DINOSIM,
        name="Dino Sim",
        dependencies=DependencyContribution(
            requires=(CORE_VERBS,),
            recommends=(LIFESIM, COLONYSIM, STORYTELLER),
        ),
        ecs=EcsContribution(
            components=(
                DinosimPolicyComponent,
                DinosaurComponent,
                SpeciesComponent,
                FossilFragmentComponent,
                SpeciesIdentificationComponent,
                AncientSampleComponent,
                CloneCandidateComponent,
                EggComponent,
                FertilityComponent,
                ReptileProcreationComponent,
                IncubationComponent,
                HatchlingComponent,
                TrackComponent,
                ScentComponent,
                BaitComponent,
                TranquilizerComponent,
                TamingComponent,
                TrustComponent,
                FearComponent,
                TrainingComponent,
                CommandComponent,
                MountComponent,
                CompanionComponent,
                GuardBehaviorComponent,
                HuntBehaviorComponent,
                RecallComponent,
                EnclosureComponent,
                FenceComponent,
                GateComponent,
                ReinforcementComponent,
                FeedingPenComponent,
                QuarantinePenComponent,
                EscapeRiskComponent,
                BreachComponent,
                StampedeComponent,
                ContainmentProtocolComponent,
                KaijuComponent,
                SettlementDamageComponent,
                CreatureAttackComponent,
                RoarComponent,
                ChargeComponent,
                GrappleComponent,
                TrampleComponent,
                ArmorPlateComponent,
                WeakPointComponent,
                PackHuntComponent,
                ApexPredatorComponent,
                ArmyResponseComponent,
                FeedStoreComponent,
                CreatureProductComponent,
                HideComponent,
                BoneComponent,
                ToxinComponent,
                CreatureMilkComponent,
                RanchLaborComponent,
                GuardAnimalComponent,
            )
        ),
        commands=CommandContribution(
            action_handlers=(
                IdentifyFossilHandler,
                ExtractAncientSampleHandler,
                PrepareCloneHandler,
                LayEggHandler,
                FertilizeEggHandler,
                IncubateEggHandler,
                HatchEggHandler,
                TrackCreatureHandler,
                SetBaitHandler,
                TranquilizeCreatureHandler,
                ApproachCreatureHandler,
                TameCreatureHandler,
                TrainCommandHandler,
                MountCreatureHandler,
                CommandCompanionHandler,
                RecallCreatureHandler,
                BuildEnclosureHandler,
                RepairFenceHandler,
                ReinforceGateHandler,
                LockPenHandler,
                OpenPenHandler,
                TriggerContainmentHandler,
                RecaptureCreatureHandler,
                HideFromCreatureHandler,
                EvacuateRoomHandler,
                DodgeCreatureHandler,
                FightCreatureHandler,
                TargetWeakPointHandler,
                DriveOffPredatorHandler,
                CallForHelpHandler,
                SignalArmyHandler,
                RepairDamageHandler,
                StockFeedHandler,
                CollectEggHandler,
                HarvestProductHandler,
                AssignRanchWorkHandler,
                AssignGuardHandler,
            ),
            typed_events=(
                FossilIdentifiedEvent,
                AncientSampleExtractedEvent,
                ClonePreparedEvent,
                EggLaidEvent,
                EggFertilizedEvent,
                EggIncubatedEvent,
                EggHatchedEvent,
                CreatureTrackedEvent,
                BaitSetEvent,
                CreatureTranquilizedEvent,
                TamingProgressedEvent,
                CreatureTamedEvent,
                CommandTrainedEvent,
                CreatureMountedEvent,
                CompanionCommandedEvent,
                CreatureRecalledEvent,
                EnclosureBuiltEvent,
                FenceRepairedEvent,
                GateReinforcedEvent,
                PenLockedEvent,
                PenOpenedEvent,
                ContainmentTriggeredEvent,
                CreatureEscapedEvent,
                CreatureRecapturedEvent,
                StampedeStartedEvent,
                RoomEvacuatedEvent,
                HiddenFromCreatureEvent,
                CreatureAttackedEvent,
                CreatureRoaredEvent,
                CreatureChargedEvent,
                CreatureTrampledEvent,
                WeakPointHitEvent,
                ApexPredatorAppearedEvent,
                KaijuArrivedEvent,
                ArmyCalledEvent,
                SettlementDamagedEvent,
                PredatorDrivenOffEvent,
                SettlementDamageRepairedEvent,
                FeedStockedEvent,
                CreatureProductCollectedEvent,
                RanchWorkAssignedEvent,
                GuardAssignedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(install_dinosim,)),
        content=ContentContribution(
            prompt_fragments=(dinosim_fragments,),
            world_generators=(DINOSIM_DEMO,),
        ),
    )


def toonsim_plugin() -> Plugin:
    return Plugin(
        id=TOONSIM,
        name="Toon Sim",
        ecs=EcsContribution(
            components=(SpritePosition, SpriteImage, SpriteLayer, SpriteScale),
        ),
        commands=CommandContribution(
            action_handlers=(MoveSpriteHandler,),
            typed_events=(SpriteMovedEvent,),
        ),
        runtime=RuntimeContribution(service_factories=(install_toonsim,)),
    )


def dragonsim_plugin() -> Plugin:
    return Plugin(
        id=DRAGONSIM,
        name="Dragon Sim",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(
            components=(
                PointOfInterestComponent,
                DiscoveryComponent,
                QuestComponent,
                QuestStageComponent,
                QuestObjectiveComponent,
                QuestRewardComponent,
                FactionComponent,
                FactionReputationComponent,
            ),
            edges=(MemberOf,),
        ),
        commands=CommandContribution(
            action_handlers=(
                DiscoverLocationHandler,
                AcceptQuestHandler,
                CompleteObjectiveHandler,
                JoinFactionHandler,
                LeaveFactionHandler,
            ),
            typed_events=(
                LocationDiscoveredEvent,
                QuestAcceptedEvent,
                QuestObjectiveCompletedEvent,
                QuestCompletedEvent,
                FactionJoinedEvent,
                FactionLeftEvent,
            ),
        ),
        content=ContentContribution(
            prompt_fragments=(dragonsim_fragments,),
            world_generators=(DRAGONSIM_DEMO,),
        ),
    )


def daggersim_plugin() -> Plugin:
    return Plugin(
        id=DAGGERSIM,
        name="Dagger Sim",
        dependencies=DependencyContribution(
            requires=(CORE_VERBS,),
            recommends=(WORLDGEN,),
        ),
        ecs=EcsContribution(
            components=(
                ProceduralSiteComponent,
                UnrealizedLocationComponent,
                ExpansionHookComponent,
                RumorComponent,
                RumorSourceComponent,
                RumorReliabilityComponent,
                RumorTargetComponent,
                TravelHubComponent,
                TravelModeComponent,
                TravelPlanComponent,
                InstitutionComponent,
                InstitutionServiceComponent,
                QuestTemplateComponent,
                GeneratedQuestComponent,
                QuestDeadlineComponent,
                DaggerQuestRewardComponent,
                BankComponent,
                BankAccountComponent,
                LoanComponent,
                DebtComponent,
                LawRegionComponent,
                CrimeRecordComponent,
                BountyComponent,
                ClassTemplateComponent,
                CustomClassComponent,
                SpellTemplateComponent,
                CustomSpellComponent,
                EnchantedItemComponent,
                LanguageSkillComponent,
                CreatureLanguageComponent,
                HostilityComponent,
                PacifiedComponent,
                SupernaturalAfflictionComponent,
                FeedingNeedComponent,
                WereformComponent,
                DungeonComponent,
                DungeonRoomComponent,
                DungeonObjectiveComponent,
                SecretDoorComponent,
                AutomapComponent,
                RecallAnchorComponent,
                RestRiskComponent,
                DialogueApproachComponent,
                EtiquetteSkillComponent,
                StreetwiseSkillComponent,
                SocialRegisterComponent,
                ConversationToneComponent,
            ),
            edges=(TravelRoute, MemberOfInstitution),
        ),
        commands=CommandContribution(
            action_handlers=(
                ExpandSiteHandler,
                AskRumorHandler,
                InvestigateRumorHandler,
                PlanTravelHandler,
                JoinInstitutionHandler,
                UseInstitutionServiceHandler,
                AskForWorkHandler,
                AcceptGeneratedQuestHandler,
                CompleteGeneratedQuestHandler,
                OpenBankAccountHandler,
                DepositHandler,
                WithdrawHandler,
                TakeLoanHandler,
                RepayLoanHandler,
                CommitCrimeHandler,
                PayFineHandler,
                CreateCustomClassHandler,
                CreateSpellHandler,
                EnchantItemHandler,
                CastSpellHandler,
                AttemptPacifyHandler,
                ContractAfflictionHandler,
                TransformHandler,
                RequestDungeonHandler,
                EnterDungeonHandler,
                SearchRoomHandler,
                OpenSecretDoorHandler,
                MarkPathHandler,
                ViewMapHandler,
                SetRecallHandler,
                UseRecallHandler,
                RestHandler,
                LeaveDungeonHandler,
            ),
            typed_events=(
                ExpansionRequestedEvent,
                GeneratedSiteInstantiatedEvent,
                RumorHeardEvent,
                RumorVerifiedEvent,
                RumorDisprovenEvent,
                RumorBecameExpansionEvent,
                TravelStartedEvent,
                TravelCompletedEvent,
                InstitutionJoinedEvent,
                InstitutionServiceUsedEvent,
                QuestGeneratedEvent,
                DaggerQuestAcceptedEvent,
                DaggerQuestCompletedEvent,
                QuestFailedEvent,
                AccountOpenedEvent,
                DepositMadeEvent,
                WithdrawalMadeEvent,
                LoanIssuedEvent,
                LoanRepaidEvent,
                LoanDefaultedEvent,
                CrimeCommittedEvent,
                BountyPostedEvent,
                FinePaidEvent,
                CustomClassCreatedEvent,
                SpellCreatedEvent,
                ItemEnchantedEvent,
                SpellCastEvent,
                PacificationAttemptedEvent,
                CreaturePacifiedEvent,
                AfflictionContractedEvent,
                FeedingNeedChangedEvent,
                TransformationStartedEvent,
                DungeonRequestedEvent,
                DungeonGeneratedEvent,
                DungeonEnteredEvent,
                DungeonRoomDiscoveredEvent,
                SecretDoorFoundEvent,
                RecallAnchorSetEvent,
                RecallUsedEvent,
                DungeonObjectiveFoundEvent,
                DungeonExitedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(install_daggersim,)),
        content=ContentContribution(
            prompt_fragments=(daggersim_fragments,),
            world_generators=(DAGGERSIM_DEMO,),
        ),
    )


def voidsim_plugin() -> Plugin:
    return Plugin(
        id=VOIDSIM,
        name="Void Sim",
        dependencies=DependencyContribution(
            requires=(CORE_VERBS,),
            recommends=(WORLDGEN, ENVIRONMENT, BARBARIANSIM),
        ),
        ecs=EcsContribution(
            components=(
                ShipComponent,
                StationComponent,
                HabitatModuleComponent,
                AirlockComponent,
                BulkheadComponent,
                PressurizedComponent,
                LifeSupportComponent,
                ShipSystemComponent,
                PowerGridComponent,
                OxygenComponent,
                RadiationShieldComponent,
                ChaosInfluenceComponent,
                ChaosWardComponent,
                ChaosMutationPressureComponent,
                RadiationMutationPressureComponent,
                CyberneticMutationPressureComponent,
                StarSystemComponent,
                OrbitalBodyComponent,
                OrbitComponent,
                NavigationRouteComponent,
                JumpDriveComponent,
                FuelComponent,
                SensorComponent,
                DistressSignalComponent,
                AstrogationComponent,
            ),
            edges=(DockedTo, JumpRoute),
        ),
        commands=CommandContribution(
            action_handlers=(
                OpenAirlockHandler,
                CycleAirlockHandler,
                SealBulkheadHandler,
                RepairSystemHandler,
                ReroutePowerHandler,
                InspectShipSystemHandler,
                DockHandler,
                UndockHandler,
                EvacuateModuleHandler,
                PlotCourseHandler,
                JumpHandler,
                ScanHandler,
                AnswerDistressSignalHandler,
                RefuelHandler,
                EnterOrbitHandler,
                LeaveOrbitHandler,
                LandHandler,
                LaunchHandler,
            ),
            typed_events=(
                AirlockCycledEvent,
                PressureChangedEvent,
                LifeSupportFailedEvent,
                PowerReroutedEvent,
                ShipSystemDamagedEvent,
                ShipSystemRepairedEvent,
                DockingCompletedEvent,
                ModuleEvacuatedEvent,
                CoursePlottedEvent,
                JumpStartedEvent,
                JumpCompletedEvent,
                FuelChangedEvent,
                SignalDetectedEvent,
                NavigationHazardEncounteredEvent,
                OrbitEnteredEvent,
                LandingCompletedEvent,
                ChaosInfluenceAppliedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(install_voidsim,)),
        content=ContentContribution(
            prompt_fragments=(voidsim_fragments,),
            world_generators=(VOIDSIM_DEMO,),
        ),
    )


def nukesim_plugin() -> Plugin:
    return Plugin(
        id=NUKESIM,
        name="Nuke Sim",
        dependencies=DependencyContribution(
            requires=(CORE_VERBS,),
            recommends=(COLONYSIM, VOIDSIM),
        ),
        ecs=EcsContribution(
            components=(
                RadiationSourceComponent,
                RadiationDoseComponent,
                RadiationSicknessComponent,
                RadProtectionComponent,
                DecontaminationComponent,
                RadMedicineComponent,
                MutationThresholdComponent,
                MutationResistanceComponent,
                MutationComponent,
                RadiationMutationPressureComponent,
                ScavengeSiteComponent,
                LootTableComponent,
                JunkComponent,
                ResourceStackComponent,
            )
        ),
        commands=CommandContribution(
            action_handlers=(
                ScanRadiationHandler,
                SealRadiationSourceHandler,
                DecontaminateHandler,
                UseRadMedicineHandler,
                ScavengeHandler,
                ScrapItemHandler,
                StabilizeMutationHandler,
            ),
            typed_events=(
                RadiationExposureEvent,
                RadiationSicknessChangedEvent,
                RadiationScannedEvent,
                RadiationSourceSealedEvent,
                DecontaminationAppliedEvent,
                RadMedicineUsedEvent,
                MutationPressureChangedEvent,
                MutationManifestedEvent,
                MutationStabilizedEvent,
                SiteScavengedEvent,
                LootFoundEvent,
                HazardTriggeredEvent,
                ItemScrappedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(install_nukesim,)),
        content=ContentContribution(
            prompt_fragments=(nukesim_fragments,),
            world_generators=(NUKESIM_DEMO,),
        ),
    )


def storyteller_plugin() -> Plugin:
    return Plugin(
        id=STORYTELLER,
        name="Storyteller",
        dependencies=DependencyContribution(requires=(CORE_VERBS,)),
        ecs=EcsContribution(
            components=(
                StorytellerComponent,
                IncidentBudgetComponent,
                ThreatPointsComponent,
                IncidentHistoryComponent,
                IncidentComponent,
            )
        ),
        commands=CommandContribution(
            action_handlers=(ResolveIncidentHandler,),
            typed_events=(
                IncidentProposedEvent,
                IncidentStartedEvent,
                IncidentResolvedEvent,
            ),
        ),
        runtime=RuntimeContribution(service_factories=(install_storyteller,)),
        content=ContentContribution(prompt_fragments=(storyteller_fragments,)),
    )


def mcp_plugin() -> Plugin:
    return Plugin(
        id=MCP,
        name="MCP Server",
        default_enabled=False,
        ecs=EcsContribution(components=(MCPControllerComponent,)),
    )


def bunnyland_plugins() -> list[Plugin]:
    return [
        core_verbs_plugin(),
        lifesim_plugin(),
        memory_plugin(),
        worldgen_plugin(),
        environment_plugin(),
        mechanisms_plugin(),
        social_plugin(),
        policy_plugin(),
        persona_plugin(),
        colonysim_plugin(),
        barbariansim_plugin(),
        gardensim_plugin(),
        dinosim_plugin(),
        toonsim_plugin(),
        dragonsim_plugin(),
        daggersim_plugin(),
        voidsim_plugin(),
        nukesim_plugin(),
        storyteller_plugin(),
        mcp_plugin(),
    ]


__all__ = [
    "BARBARIANSIM",
    "CORE_VERBS",
    "COLONYSIM",
    "DAGGERSIM",
    "DINOSIM",
    "DRAGONSIM",
    "ENVIRONMENT",
    "GARDENSIM",
    "LIFESIM",
    "MCP",
    "MECHANISMS",
    "MEMORY",
    "NUKESIM",
    "PERSONA",
    "POLICY",
    "SOCIAL",
    "STORYTELLER",
    "TOONSIM",
    "VOIDSIM",
    "WORLDGEN",
    "barbariansim_plugin",
    "bunnyland_plugins",
    "colonysim_plugin",
    "dinosim_plugin",
    "core_verbs_plugin",
    "daggersim_plugin",
    "dragonsim_plugin",
    "environment_plugin",
    "gardensim_plugin",
    "storyteller_plugin",
    "lifesim_plugin",
    "mechanisms_plugin",
    "memory_plugin",
    "mcp_plugin",
    "nukesim_plugin",
    "persona_plugin",
    "policy_plugin",
    "social_plugin",
    "toonsim_plugin",
    "voidsim_plugin",
    "worldgen_plugin",
]
