"""Stable identifiers for bundled Bunnyland plugins."""

CORE_VERBS = "bunnyland.core_verbs"
MEDIA = "bunnyland.media"
LIFESIM = "bunnyland.lifesim"
MEMORY = "bunnyland.memory"
WORLDGEN = "bunnyland.worldgen"
ENVIRONMENT = "bunnyland.environment"
MECHANISMS = "bunnyland.mechanisms"
SOCIAL = "bunnyland.social"
HISTORY = "bunnyland.history"
POLICY = "bunnyland.policy"
PERSONA = "bunnyland.persona"
PROMPT_FILTERS = "bunnyland.prompt_filters"
COLONYSIM = "bunnyland.colonysim"
BARBARIANSIM = "bunnyland.barbariansim"
GARDENSIM = "bunnyland.gardensim"
DINOSIM = "bunnyland.dinosim"
DRAGONSIM = "bunnyland.dragonsim"
DAGGERSIM = "bunnyland.daggersim"
VOIDSIM = "bunnyland.voidsim"
NUKESIM = "bunnyland.nukesim"
NEONSIM = "bunnyland.neonsim"
TOONSIM = "bunnyland.toonsim"
STORYTELLER = "bunnyland.storyteller"
IMAGEGEN = "bunnyland.imagegen"
MCP = "bunnyland.mcp"
CHECKPOINTS = "bunnyland.checkpoints"
DISCORD = "bunnyland.discord"

__all__ = [name for name in globals() if name.isupper()]
