"""bunnyland core: ECS primitives, components, edges, events, commands, world actor.

This package wraps the synchronous Relics ECS with the async, event-driven,
command-queue architecture described in the bunnyland specification.
"""

from .commands import (
    Command,
    CommandCost,
    Lane,
    MoveCommand,
    OnInsufficientPoints,
    SayCommand,
    SpeechIntent,
    SubmittedCommand,
    TellCommand,
    WaitCommand,
    build_submitted_command,
)
from .components import (
    ActionPointsComponent,
    ButtonComponent,
    CharacterComponent,
    ContainerComponent,
    DeadComponent,
    DescriptionComponent,
    DoorComponent,
    DownedComponent,
    FocusPointsComponent,
    HealthComponent,
    IdentityComponent,
    InitiativeComponent,
    InventoryComponent,
    KeyComponent,
    LifecycleComponent,
    LockableComponent,
    PortableComponent,
    ReadableComponent,
    RoomComponent,
    SleepingComponent,
    SuspendedComponent,
    WorldClockComponent,
    WritableComponent,
)
from .controllers import (
    DiscordControllerComponent,
    LLMControllerComponent,
    SuspendedControllerComponent,
)
from .ecs import (
    container_of,
    contents,
    parse_entity_id,
    reachable_ids,
    replace_component,
    spawn_entity,
)
from .edges import ContainmentMode, Contains, ControlledBy, ExitTo, Holding, Wearing
from .events import DomainEvent, EventBus, EventVisibility
from .handlers import (
    HandlerContext,
    HandlerResult,
    MoveHandler,
    PutHandler,
    SayHandler,
    SleepHandler,
    TakeHandler,
    TellHandler,
    UseHandler,
    WaitHandler,
    WakeHandler,
    WriteHandler,
    infer_intent,
)
from .queue import CommandQueues
from .world_actor import WorldActor

__all__ = [
    "ActionPointsComponent",
    "ButtonComponent",
    "CharacterComponent",
    "Command",
    "CommandCost",
    "CommandQueues",
    "ContainerComponent",
    "Contains",
    "ContainmentMode",
    "ControlledBy",
    "DeadComponent",
    "DescriptionComponent",
    "DiscordControllerComponent",
    "DomainEvent",
    "DoorComponent",
    "DownedComponent",
    "EventBus",
    "EventVisibility",
    "ExitTo",
    "FocusPointsComponent",
    "HandlerContext",
    "HandlerResult",
    "HealthComponent",
    "Holding",
    "IdentityComponent",
    "InitiativeComponent",
    "InventoryComponent",
    "KeyComponent",
    "LLMControllerComponent",
    "Lane",
    "LifecycleComponent",
    "LockableComponent",
    "MoveCommand",
    "MoveHandler",
    "OnInsufficientPoints",
    "PortableComponent",
    "PutHandler",
    "ReadableComponent",
    "RoomComponent",
    "SayCommand",
    "SayHandler",
    "SleepHandler",
    "SleepingComponent",
    "SpeechIntent",
    "SubmittedCommand",
    "SuspendedComponent",
    "SuspendedControllerComponent",
    "TakeHandler",
    "TellCommand",
    "TellHandler",
    "UseHandler",
    "WaitCommand",
    "WaitHandler",
    "WakeHandler",
    "Wearing",
    "WorldActor",
    "WorldClockComponent",
    "WritableComponent",
    "WriteHandler",
    "build_submitted_command",
    "container_of",
    "contents",
    "infer_intent",
    "parse_entity_id",
    "reachable_ids",
    "replace_component",
    "spawn_entity",
]
