"""daggersim generation contribution compatibility surface."""

from ...worldgen.enrichment import ComponentPlanEnricher, DaggerWorldgenHook

CAPABILITIES = (
    "bunnyland.daggersim.affliction-stigma",
    "bunnyland.daggersim.automap",
    "bunnyland.daggersim.bank",
    "bunnyland.daggersim.camping",
    "bunnyland.daggersim.class-template",
    "bunnyland.daggersim.conversation-tone",
    "bunnyland.daggersim.creature-language",
    "bunnyland.daggersim.cure-quest-hook",
    "bunnyland.daggersim.custom-class",
    "bunnyland.daggersim.custom-spell",
    "bunnyland.daggersim.dagger-quest-reward",
    "bunnyland.daggersim.dialogue-approach",
    "bunnyland.daggersim.dungeon",
    "bunnyland.daggersim.dungeon-objective",
    "bunnyland.daggersim.enchanted-item",
    "bunnyland.daggersim.etiquette-skill",
    "bunnyland.daggersim.expansion-hook",
    "bunnyland.daggersim.feeding-need",
    "bunnyland.daggersim.generated-quest",
    "bunnyland.daggersim.hostility",
    "bunnyland.daggersim.ingredient",
    "bunnyland.daggersim.institution",
    "bunnyland.daggersim.institution-dues",
    "bunnyland.daggersim.institution-reputation",
    "bunnyland.daggersim.institution-service",
    "bunnyland.daggersim.language-skill",
    "bunnyland.daggersim.law-region",
    "bunnyland.daggersim.legal-reputation",
    "bunnyland.daggersim.lodging",
    "bunnyland.daggersim.potion-maker",
    "bunnyland.daggersim.procedural-site",
    "bunnyland.daggersim.property-deed",
    "bunnyland.daggersim.quest-deadline",
    "bunnyland.daggersim.quest-template",
    "bunnyland.daggersim.recall-anchor",
    "bunnyland.daggersim.recharge-service",
    "bunnyland.daggersim.regional-reputation",
    "bunnyland.daggersim.rest-risk",
    "bunnyland.daggersim.rumor",
    "bunnyland.daggersim.rumor-reliability",
    "bunnyland.daggersim.rumor-source",
    "bunnyland.daggersim.rumor-target",
    "bunnyland.daggersim.secret-door",
    "bunnyland.daggersim.service-access",
    "bunnyland.daggersim.social-register",
    "bunnyland.daggersim.spell-template",
    "bunnyland.daggersim.streetwise-skill",
    "bunnyland.daggersim.supernatural-affliction",
    "bunnyland.daggersim.travel-hub",
    "bunnyland.daggersim.travel-interruption",
    "bunnyland.daggersim.travel-mode",
    "bunnyland.daggersim.travel-supply",
    "bunnyland.daggersim.unrealized-location",
)
ALIASES = {
    "affliction-stigma": "bunnyland.daggersim.affliction-stigma",
    "automap": "bunnyland.daggersim.automap",
    "bank": "bunnyland.daggersim.bank",
    "camping": "bunnyland.daggersim.camping",
    "class-template": "bunnyland.daggersim.class-template",
    "conversation-tone": "bunnyland.daggersim.conversation-tone",
    "creature-language": "bunnyland.daggersim.creature-language",
    "cure-quest-hook": "bunnyland.daggersim.cure-quest-hook",
    "custom-class": "bunnyland.daggersim.custom-class",
    "custom-spell": "bunnyland.daggersim.custom-spell",
    "dagger-quest-reward": "bunnyland.daggersim.dagger-quest-reward",
    "dialogue-approach": "bunnyland.daggersim.dialogue-approach",
    "dungeon": "bunnyland.daggersim.dungeon",
    "dungeon-objective": "bunnyland.daggersim.dungeon-objective",
    "enchanted-item": "bunnyland.daggersim.enchanted-item",
    "etiquette-skill": "bunnyland.daggersim.etiquette-skill",
    "expansion-hook": "bunnyland.daggersim.expansion-hook",
    "feeding-need": "bunnyland.daggersim.feeding-need",
    "generated-quest": "bunnyland.daggersim.generated-quest",
    "hostility": "bunnyland.daggersim.hostility",
    "ingredient": "bunnyland.daggersim.ingredient",
    "institution": "bunnyland.daggersim.institution",
    "institution-dues": "bunnyland.daggersim.institution-dues",
    "institution-reputation": "bunnyland.daggersim.institution-reputation",
    "institution-service": "bunnyland.daggersim.institution-service",
    "language-skill": "bunnyland.daggersim.language-skill",
    "law-region": "bunnyland.daggersim.law-region",
    "legal-reputation": "bunnyland.daggersim.legal-reputation",
    "lodging": "bunnyland.daggersim.lodging",
    "potion-maker": "bunnyland.daggersim.potion-maker",
    "procedural-site": "bunnyland.daggersim.procedural-site",
    "property-deed": "bunnyland.daggersim.property-deed",
    "quest-deadline": "bunnyland.daggersim.quest-deadline",
    "quest-template": "bunnyland.daggersim.quest-template",
    "recall-anchor": "bunnyland.daggersim.recall-anchor",
    "recharge-service": "bunnyland.daggersim.recharge-service",
    "regional-reputation": "bunnyland.daggersim.regional-reputation",
    "rest-risk": "bunnyland.daggersim.rest-risk",
    "rumor": "bunnyland.daggersim.rumor",
    "rumor-reliability": "bunnyland.daggersim.rumor-reliability",
    "rumor-source": "bunnyland.daggersim.rumor-source",
    "rumor-target": "bunnyland.daggersim.rumor-target",
    "secret-door": "bunnyland.daggersim.secret-door",
    "service-access": "bunnyland.daggersim.service-access",
    "social-register": "bunnyland.daggersim.social-register",
    "spell-template": "bunnyland.daggersim.spell-template",
    "streetwise-skill": "bunnyland.daggersim.streetwise-skill",
    "supernatural-affliction": "bunnyland.daggersim.supernatural-affliction",
    "travel-hub": "bunnyland.daggersim.travel-hub",
    "travel-interruption": "bunnyland.daggersim.travel-interruption",
    "travel-mode": "bunnyland.daggersim.travel-mode",
    "travel-supply": "bunnyland.daggersim.travel-supply",
    "unrealized-location": "bunnyland.daggersim.unrealized-location",
}
GENERATION_ENRICHER = ComponentPlanEnricher(DaggerWorldgenHook, provided_capabilities=CAPABILITIES)

__all__ = ["GENERATION_ENRICHER", "DaggerWorldgenHook"]
